import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { DatabaseSync, type StatementSync, type SQLInputValue } from "node:sqlite";
import { D1FinancialStore, type D1DatabaseLike, type D1Result, type D1Rows, type D1Statement } from "../src/core/d1Store.ts";
import { RevenueGuard, type FaultInjector } from "../src/core/guard.ts";
import type { Authorization, PaymentProvider, PaymentRequirement, Settlement, SettlementLookup } from "../src/core/paymentProvider.ts";
import type { PaymentVerification, RequestContext } from "../src/core/types.ts";
import type { RevenueGuardConfig } from "../src/core/pricing.ts";
import { encodeX402Header, paymentRequired } from "../src/index.ts";

type ContractVectors={version:number;vectors:Record<string,Record<string,unknown>>};
const contractVectors=JSON.parse(readFileSync(
  new URL("./security_contract_vectors.json",import.meta.url),"utf8",
)) as ContractVectors;
const requiredContractVectors=[
  "zero_price_positive_cost","under_authorization","wrong_merchant",
  "wrong_network","wrong_asset","payment_replay","settlement_failure",
  "kill_switch","budget_race","ambiguous_settlement","restart_recovery",
];
assert.equal(contractVectors.version,1);
for(const id of requiredContractVectors)assert.ok(contractVectors.vectors[id],`missing contract vector: ${id}`);

class SqliteStatement implements D1Statement {
  private statement:StatementSync;private args:SQLInputValue[]=[];
  constructor(statement:StatementSync){this.statement=statement;}
  bind(...values:unknown[]):D1Statement{this.args=values as SQLInputValue[];return this;}
  async run():Promise<D1Result>{try{const out=this.statement.run(...this.args);return{success:true,meta:{changes:Number(out.changes)}};}catch{return{success:false,meta:{changes:0}};}}
  async first<T>():Promise<T|null>{return(this.statement.get(...this.args) as T|undefined)??null;}
  async all<T>():Promise<D1Rows<T>>{return{results:this.statement.all(...this.args) as T[]};}
}
class SqliteD1 implements D1DatabaseLike {
  readonly raw:DatabaseSync;constructor(path:string){this.raw=new DatabaseSync(path);this.raw.prepare("PRAGMA journal_mode=WAL").get();this.raw.prepare("PRAGMA busy_timeout=5000").get();}
  prepare(sql:string):D1Statement{return new SqliteStatement(this.raw.prepare(sql));}close():void{this.raw.close();}
}

class DurableProvider implements PaymentProvider {
  readonly movesRealMoney=true;private db:DatabaseSync;private loseResponse:boolean;private unknownLookup:boolean;
  constructor(path:string,loseResponse=false,unknownLookup=false){this.db=new DatabaseSync(path);this.loseResponse=loseResponse;this.unknownLookup=unknownLookup;this.db.prepare("CREATE TABLE IF NOT EXISTS effects(settlement_id TEXT PRIMARY KEY,amount REAL NOT NULL,payer TEXT NOT NULL)").run();}
  terms(){return{asset:"0xasset",network:"eip155:84532",payTo:"0xmerchant",scheme:"upto" as const};}
  async authorizePayment(_r:string,maximum:number):Promise<Authorization>{return{authorized:true,payer:"payer",maxAmount:maximum,reason:""};}
  async settlePayment(_r:string,actual:number,id:string,_q:PaymentRequirement):Promise<Settlement>{this.db.prepare("INSERT OR IGNORE INTO effects VALUES(?,?,?)").run(id,actual,"payer");if(this.loseResponse)throw new Error("settlement response loss");return{settled:true,payer:"payer",amount:actual,transaction:id,reason:"",disposition:"SETTLED"};}
  async lookupSettlement(id:string):Promise<SettlementLookup>{if(this.unknownLookup)return{status:"UNKNOWN",payer:"",amount:0,transaction:"",reason:"status unavailable"};const row=this.db.prepare("SELECT amount,payer FROM effects WHERE settlement_id=?").get(id) as {amount:number;payer:string}|undefined;return row?{status:"SETTLED",payer:row.payer,amount:row.amount,transaction:id,reason:""}:{status:"FINAL_FAILURE",payer:"",amount:0,transaction:"",reason:"not found"};}
  effects():number{return Number((this.db.prepare("SELECT COUNT(*) AS n FROM effects").get() as {n:number}).n);}
  exportPaymentProof(_reference:string):unknown{return{accepted:{scheme:"upto"}};}importPaymentProof(_reference:string,_payload:unknown):boolean{return true;}
  async verifyPayment(reference:string):Promise<PaymentVerification>{return{status:"paid",amount:1,payer:"payer",reference};}async getPaymentAmount():Promise<number>{return 1;}async getPayer():Promise<string>{return"payer";}async recordTransaction():Promise<void>{}
}
class CrashAt implements FaultInjector {private point:string;constructor(point:string){this.point=point;}checkpoint(name:string):void{if(name===this.point)throw new Error(`CRASH:${name}`);}}

const config:RevenueGuardConfig={minGrossMarginRatio:.7,minPriceMultiplier:3,perRequestMaxCost:.5,dailyMaxCost:.5,monthlyMaxCost:.5,perUserDailyCost:.5,perProductDailyCost:.5,rateLimitWindowSeconds:60,rateLimitMaxRequests:100,circuitBreakerFailureThreshold:3,circuitBreakerWindowSeconds:60,circuitBreakerCooldownSeconds:60,cacheDefaultTtlSeconds:0};
function context(upstream:()=>Promise<unknown>):RequestContext{return{productId:"early-3426536d88daa242",identityKind:"api_key",identityValue:"user",authenticated:true,requestPayload:{q:"durable"},pricePerCall:.1,estimatedCost:.01,paymentReference:"proof",requestId:"stable-request-0001",upstreamName:"upstream",upstream,actualCost:()=>.005};}
function files():{ledger:string;provider:string}{const dir=mkdtempSync(join(tmpdir(),"moneyai-recovery-"));return{ledger:join(dir,"ledger.db"),provider:join(dir,"provider.db")};}
function guard(path:string,provider:PaymentProvider,faults:FaultInjector|null=null,env:Record<string,string>={REAL_PAYMENTS_ENABLED:"true"}):RevenueGuard{return new RevenueGuard(new D1FinancialStore(new SqliteD1(path)),config,provider,env,undefined,faults);}

test("restart after upstream never duplicates upstream side effect",async()=>{const f=files();let calls=0;let key="";const upstream=async(idempotencyKey?:string)=>{calls++;key=idempotencyKey??"";return{value:1};};await assert.rejects(()=>guard(f.ledger,new DurableProvider(f.provider),new CrashAt("after_upstream")).processRequest(context(upstream)),/CRASH/);const retry=await guard(f.ledger,new DurableProvider(f.provider)).processRequest(context(upstream));assert.equal(retry.allowed,false);assert.equal(calls,1);assert.equal(key,"stable-request-0001:upstream");});

test("settlement response loss recovers by authoritative lookup without another effect",async()=>{const f=files();let calls=0;const upstream=async()=>{calls++;return{value:2};};await assert.rejects(()=>guard(f.ledger,new DurableProvider(f.provider,true)).processRequest(context(upstream)),/response loss/);const provider=new DurableProvider(f.provider);const retry=await guard(f.ledger,provider).processRequest(context(upstream));assert.equal(retry.allowed,true);assert.equal(provider.effects(),1);assert.equal(calls,1);});

test("duplicate retry after settled performs durable result replay",async()=>{const f=files();let calls=0;const upstream=async()=>{calls++;return{value:3};};const first=await guard(f.ledger,new DurableProvider(f.provider)).processRequest(context(upstream));assert.equal(first.allowed,true);const provider=new DurableProvider(f.provider);const retry=await guard(f.ledger,provider).processRequest(context(upstream));assert.deepEqual(retry.result,{value:3});assert.equal(provider.effects(),1);assert.equal(calls,1);});

test("recovery lease conflict permits one recovery owner",async()=>{const f=files();const db=new SqliteD1(f.ledger);const store=new D1FinancialStore(db);const now=Date.now();await store.createOperation({operationId:"lease-operation",requestId:"lease-request",requirementId:"lease-requirement",productId:"p",requestHash:"h",artifactHash:"a",paymentProvider:"x402",paymentReference:"r",requirementJson:"{}",payer:"",reservationId:"reserve",upstreamOperationId:"upstream",settlementId:"settle",state:"RECOVERY_REQUIRED",authorizedAmount:.1,reservedAmount:.01,actualCost:.005,settlementAmount:null,resultDigest:"d",errorCode:"UNKNOWN",version:0,recoveryOwner:"",recoveryLeaseUntil:0,createdAt:now,updatedAt:now});assert.equal(await store.claimRecovery("lease-operation","one",now,now+30_000),true);assert.equal(await store.claimRecovery("lease-operation","two",now+1,now+30_000),false);});

test("durable result replay survives fresh store and provider instances",async()=>{const f=files();let calls=0;const upstream=async()=>{calls++;return{durable:"yes"};};await guard(f.ledger,new DurableProvider(f.provider)).processRequest(context(upstream));const replay=await guard(f.ledger,new DurableProvider(f.provider)).processRequest(context(upstream));assert.deepEqual(replay.result,{durable:"yes"});assert.equal(calls,1);});

test("unknown financial state blocks result and creates no new settlement",async()=>{const f=files();let calls=0;const upstream=async()=>{calls++;return{value:4};};await assert.rejects(()=>guard(f.ledger,new DurableProvider(f.provider,true)).processRequest(context(upstream)),/response loss/);const provider=new DurableProvider(f.provider,false,true);const retry=await guard(f.ledger,provider).processRequest(context(upstream));assert.equal(retry.allowed,false);assert.match(retry.reason,/unknown financial state/);assert.equal(provider.effects(),1);assert.equal(calls,1);});

test("reservation recovery resumes before upstream without a second reservation",async()=>{const f=files();let calls=0;const upstream=async()=>{calls++;return{value:5};};await assert.rejects(()=>guard(f.ledger,new DurableProvider(f.provider),new CrashAt("after_reservation")).processRequest(context(upstream)),/CRASH/);const retry=await guard(f.ledger,new DurableProvider(f.provider)).processRequest(context(upstream));assert.equal(retry.allowed,true);assert.equal(calls,1);});

test("kill during recovery permits lookup of an existing obligation but no duplicate exposure",async()=>{const f=files();let calls=0;const upstream=async()=>{calls++;return{value:6};};await assert.rejects(()=>guard(f.ledger,new DurableProvider(f.provider,true)).processRequest(context(upstream)),/response loss/);const provider=new DurableProvider(f.provider);const retry=await guard(f.ledger,provider,null,{REAL_PAYMENTS_ENABLED:"false",REVENUE_SYSTEM_ENABLED:"false"}).processRequest(context(upstream));assert.equal(retry.allowed,true);assert.equal(provider.effects(),1);assert.equal(calls,1);});

test("offline D1 conditional reservation 0.4 plus 0.4 plus 0.4 stays under 0.5",async()=>{const vector=contractVectors.vectors.budget_race as {ceiling:number;reservations:number[];maximumSuccessfulReservations:number};const f=files();const store=new D1FinancialStore(new SqliteD1(f.ledger));const now=Date.now();const limits={perRequest:vector.ceiling,daily:vector.ceiling,monthly:vector.ceiling,perProductDaily:vector.ceiling,perUserDaily:vector.ceiling};const row=(n:number)=>({productId:"budget-product",identityKind:"api_key",identityValue:`user-${n}`,occurredAt:now,cost:vector.reservations[n],cacheHit:false});const results=await Promise.all(vector.reservations.map((_amount,n)=>store.reserveCost(`budget-${n}`,row(n),limits)));assert.equal(results.filter(Boolean).length,vector.maximumSuccessfulReservations);assert.ok(await store.sumCost(now-1000)<=vector.ceiling);});

test("x402 v2 wire contract uses base64 PAYMENT-REQUIRED schema",()=>{const accepts=[{scheme:"upto",network:"eip155:84532",amount:"50000",asset:"0xasset",payTo:"0xmerchant",maxTimeoutSeconds:300,extra:{}}];const payload=paymentRequired("https://paid.example/mcp","payment proof required",accepts);const encoded=encodeX402Header(payload);const decoded=JSON.parse(Buffer.from(encoded,"base64").toString("utf8"));assert.equal(decoded.x402Version,2);assert.equal(decoded.resource.url,"https://paid.example/mcp");assert.deepEqual(decoded.accepts,accepts);assert.equal(typeof decoded.x402Version,"number");});

test("ledger reconciliation conserves amounts and halts product on mismatch",async()=>{const f=files();const provider=new DurableProvider(f.provider);const db=new SqliteD1(f.ledger);const store=new D1FinancialStore(db);const g=new RevenueGuard(store,config,provider,{REAL_PAYMENTS_ENABLED:"true"});await g.processRequest(context(async()=>({value:7})));const good=await store.reconcileOperation("stable-request-0001");assert.equal(good.ok,true);db.raw.prepare("UPDATE usage SET cost=.009 WHERE request_id='stable-request-0001'").run();const bad=await store.reconcileOperation("stable-request-0001");assert.equal(bad.ok,false);assert.equal(await store.isProductHalted("early-3426536d88daa242"),true);const blocked=await g.processRequest({...context(async()=>({})),requestId:"stable-request-0002"});assert.equal(blocked.stageReached,"kill_switch");});

test("financial state machine rejects and audits an impossible transition",async()=>{const f=files();const db=new SqliteD1(f.ledger);const store=new D1FinancialStore(db);const now=Date.now();await store.createOperation({operationId:"transition-op",requestId:"transition-request",requirementId:"transition-requirement",productId:"p",requestHash:"h",artifactHash:"a",paymentProvider:"none",paymentReference:"",requirementJson:"",payer:"",reservationId:"transition-reservation",upstreamOperationId:"transition-upstream",settlementId:"transition-settlement",state:"CREATED",authorizedAmount:0,reservedAmount:0,actualCost:null,settlementAmount:null,resultDigest:"",errorCode:"",version:0,recoveryOwner:"",recoveryLeaseUntil:0,createdAt:now,updatedAt:now});assert.equal(await store.transitionOperation("transition-op",0,["CREATED"],"RESULT_RELEASED"),false);const op=await store.getOperation("transition-op");assert.equal(op?.state,"CREATED");const incident=db.raw.prepare("SELECT kind FROM financial_incidents WHERE operation_id='transition-op'").get() as {kind:string};assert.equal(incident.kind,"INVALID_STATE_TRANSITION");});

test("recovery worker scans durable pending obligations after restart",async()=>{const f=files();let calls=0;const upstream=async()=>{calls++;return{scheduled:true};};await assert.rejects(()=>guard(f.ledger,new DurableProvider(f.provider,true)).processRequest(context(upstream)),/response loss/);const provider=new DurableProvider(f.provider);const fresh=guard(f.ledger,provider);const scan=await fresh.recoverPending();assert.equal(scan.scanned,1);assert.equal(scan.resolved,1);const replay=await fresh.processRequest(context(upstream));assert.equal(replay.allowed,true);assert.equal(provider.effects(),1);assert.equal(calls,1);});

test("reservation expiry releases only safe pre-upstream exposure",async()=>{const f=files();const db=new SqliteD1(f.ledger);const store=new D1FinancialStore(db);const old=Date.now()-3_600_000;const limits={perRequest:.5,daily:.5,monthly:.5,perProductDaily:.5,perUserDaily:.5};await store.reserveCost("safe-reservation",{productId:"p",identityKind:"api_key",identityValue:"u",occurredAt:old,cost:.4,cacheHit:false},limits);await store.createOperation({operationId:"safe-op",requestId:"safe-request",requirementId:"safe-requirement",productId:"p",requestHash:"h",artifactHash:"a",paymentProvider:"none",paymentReference:"",requirementJson:"",payer:"",reservationId:"safe-reservation",upstreamOperationId:"safe-upstream",settlementId:"safe-settlement",state:"COST_RESERVED",authorizedAmount:.4,reservedAmount:.4,actualCost:null,settlementAmount:null,resultDigest:"",errorCode:"",version:0,recoveryOwner:"",recoveryLeaseUntil:0,createdAt:old,updatedAt:old});assert.equal(await store.recoverExpiredSafeReservations(Date.now()-900_000),1);assert.equal((await store.getOperation("safe-op"))?.state,"FAILED_FINAL");assert.equal(await store.sumCost(0),0);await store.saveEscrow({operationId:"released-expired",resultDigest:"d",payloadJson:"{}",payloadSize:2,createdAt:old,expiresAt:old,releasedAt:old});await store.saveEscrow({operationId:"unreleased-expired",resultDigest:"d",payloadJson:"{}",payloadSize:2,createdAt:old,expiresAt:old,releasedAt:null});db.raw.prepare("INSERT INTO payment_proofs VALUES('expired-proof','{}',2,?,?)").run(old,old);assert.equal(await store.purgeExpiredSensitiveData(Date.now()),2);assert.equal(await store.getEscrow("released-expired"),null);assert.notEqual(await store.getEscrow("unreleased-expired"),null);assert.equal(Number((db.raw.prepare("SELECT COUNT(*) AS n FROM payment_proofs").get() as {n:number}).n),0);});

test("financial baseline migration adopts exact legacy schema once and is idempotent",async()=>{const f=files();const db=new SqliteD1(f.ledger);const first=new D1FinancialStore(db);await first.ensureSchema();db.raw.prepare("DROP TABLE moneyai_schema_migrations").run();const adopted=new D1FinancialStore(db);await adopted.ensureSchema();await adopted.ensureSchema();const row=db.raw.prepare("SELECT version,name,checksum FROM moneyai_schema_migrations").get() as {version:number;name:string;checksum:string};assert.equal(row.version,1);assert.equal(row.name,"financial_recovery_baseline");assert.match(row.checksum,/^[a-f0-9]{64}$/);assert.equal(Number((db.raw.prepare("SELECT COUNT(*) AS n FROM moneyai_schema_migrations").get() as {n:number}).n),1);});

test("financial migration checksum and version drift block startup",async()=>{const f=files();const db=new SqliteD1(f.ledger);const store=new D1FinancialStore(db);await store.ensureSchema();db.raw.prepare("UPDATE moneyai_schema_migrations SET checksum='wrong'").run();await assert.rejects(()=>store.ensureSchema(),/checksum mismatch/);db.raw.prepare("UPDATE moneyai_schema_migrations SET checksum='restored',version=2").run();await assert.rejects(()=>store.ensureSchema(),/version or checksum mismatch/);});

for(const checkpoint of ["after_payment_authorized","before_upstream","after_upstream","after_result_escrow","before_settlement","after_settlement_transmission","after_settlement_success_before_state","after_settled_state","before_response"]){test(`crash injection ${checkpoint} preserves at-most-once effects`,async()=>{const f=files();let calls=0;const upstream=async()=>{calls++;return{checkpoint};};const provider1=new DurableProvider(f.provider);await assert.rejects(()=>guard(f.ledger,provider1,new CrashAt(checkpoint)).processRequest(context(upstream)),/CRASH/);const provider2=new DurableProvider(f.provider);const retry=await guard(f.ledger,provider2).processRequest(context(upstream));assert.ok(calls<=1,`duplicate upstream at ${checkpoint}`);assert.ok(provider2.effects()<=1,`duplicate settlement at ${checkpoint}`);if(retry.allowed)assert.notEqual(retry.result,undefined);});}
