import test from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import worker from "../src/index.ts";
import { AppStore } from "../src/core/appStore.ts";
import { hashToken } from "../src/core/auth.ts";
import { canonicalPluginEvidence, pluginEvidenceDigest } from "../src/releaseGate/pluginEvidence.ts";
import { ReleaseGateStore } from "../src/releaseGate/store.ts";
import { runReleaseGateWorkflow } from "../src/workflows/releaseGateWorkflow.ts";
import { sqliteD1 } from "./helpers/sqlite.ts";

const hmac=async(key:string,value:string)=>{const k=await crypto.subtle.importKey("raw",new TextEncoder().encode(key),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return[...new Uint8Array(await crypto.subtle.sign("HMAC",k,new TextEncoder().encode(value)))].map(x=>x.toString(16).padStart(2,"0")).join("");};
const request=(path:string,init:RequestInit={})=>new Request(`https://app.example${path}`,init);
async function json(response:Response){return await response.json() as Record<string,unknown>;}
function schemaMatches(schema:unknown,value:unknown):boolean{if(!schema||typeof schema!=="object")return true;const s=schema as Record<string,unknown>;if(Array.isArray(s.oneOf))return s.oneOf.filter(x=>schemaMatches(x,value)).length===1;if("const"in s&&value!==s.const)return false;if(Array.isArray(s.enum)&&!s.enum.includes(value))return false;const types=Array.isArray(s.type)?s.type:[s.type];if(s.type!==undefined&&!types.some(type=>type==="null"?value===null:type==="object"?!!value&&typeof value==="object"&&!Array.isArray(value):type==="array"?Array.isArray(value):type==="integer"?Number.isInteger(value):typeof value===type))return false;if(Array.isArray(value))return !s.items||value.every(v=>schemaMatches(s.items,v));if(value&&typeof value==="object"){const o=value as Record<string,unknown>;if(Array.isArray(s.required)&&s.required.some(k=>typeof k!=="string"||!(k in o)))return false;const props=(s.properties&&typeof s.properties==="object"?s.properties:{}) as Record<string,unknown>;if(s.additionalProperties===false&&Object.keys(o).some(k=>!(k in props)))return false;return Object.entries(props).every(([k,v])=>!(k in o)||schemaMatches(v,o[k]));}return true;}

test("production-shaped release gate E2E keeps evidence private, scopes tokens, and bills exactly once",async()=>{
  const {db,raw}=sqliteD1();const app=new AppStore(db);const now=Date.now();
  await app.createUser("account_a","a@example.test","hash");await app.createUser("account_b","b@example.test","hash");
  for(const [id,user] of [["store_aaaa","account_a"],["store_bbbb","account_b"]] as const)await app.createStore({id,userId:user,name:id,storeUrl:"https://shop.example",wooKeyEnc:"encrypted",wooSecretEnc:"encrypted",plan:"free",status:"active",createdAt:now,updatedAt:now});
  const session="session-token-for-e2e";await app.createSession({tokenHash:await hashToken(session),userId:"account_a",createdAt:now,expiresAt:now+86400000});
  let fetchCalls=0;const workflow={async create({params}:{params:{runId:string}}){assert.deepEqual(Object.keys(params),["runId"]);const {runId}=params;assert.equal(fetchCalls,0);assert.equal(await app.claimReleaseRunForWorkflow(runId),true);assert.equal(await runReleaseGateWorkflow(app,runId),"published");assert.equal(fetchCalls,0);}};
  const env={FINANCIAL_DB:db,RELEASE_EVIDENCE_CURRENT_KEY:"current-root-key",RELEASE_EVIDENCE_PREVIOUS_KEY:"previous-root-key",RELEASE_EVIDENCE_PREVIOUS_KEY_EXPIRES_AT:new Date(now+600000).toISOString(),RELEASE_GATE_OWNERSHIP_SECRET:"ownership-root-key",RELEASE_GATE_WORKFLOW:workflow,REVENUE_SYSTEM_ENABLED:"true"};
  const cookie={cookie:`arw_session=${session}`};
  const unauthenticatedCredentials=await worker.fetch(request("/api/v2/stores/store_aaaa/release-credentials",{method:"POST"}),env as never);assert.equal(unauthenticatedCredentials.status,401);
  const crossOriginCredentials=await worker.fetch(request("/api/v2/stores/store_aaaa/release-credentials",{method:"POST",headers:{...cookie,origin:"https://attacker.example"}}),env as never);assert.equal(crossOriginCredentials.status,403);
  const crossTenantCredentials=await worker.fetch(request("/api/v2/stores/store_bbbb/release-credentials",{method:"POST",headers:cookie}),env as never);assert.equal(crossTenantCredentials.status,404);
  const unavailableCredentials=await worker.fetch(request("/api/v2/stores/store_aaaa/release-credentials",{method:"POST",headers:cookie}),{...env,RELEASE_EVIDENCE_CURRENT_KEY:undefined} as never);assert.equal(unavailableCredentials.status,503);
  const connectionResponse=await worker.fetch(request("/api/v2/stores/store_aaaa/release-credentials",{method:"POST",headers:cookie}),env as never);assert.equal(connectionResponse.status,200);assert.equal(connectionResponse.headers.get("cache-control"),"no-store");
  const connection=await json(connectionResponse);const derived=String(connection.evidence_key);const ownershipKey=String(connection.ownership_key);assert.deepEqual({store_id:connection.store_id,endpoint:connection.endpoint,evidence_key_id:connection.evidence_key_id},{store_id:"store_aaaa",endpoint:"https://app.example",evidence_key_id:"current"});assert.match(derived,/^[a-f0-9]{64}$/);assert.match(ownershipKey,/^[a-f0-9]{64}$/);
  const storedBeforeEvidence=JSON.stringify(raw.prepare("SELECT * FROM stores").all());assert.doesNotMatch(storedBeforeEvidence,new RegExp(`${derived}|${ownershipKey}`),"derived connection keys are not persisted in the store row");

  // Exercise the plugin's registered cron path with a mocked wp_remote_post;
  // the exact captured HTTP envelope is then passed to the Worker ingest.
  const pluginPath=JSON.stringify(new URL("../wordpress-plugin/utilityhouse-release-gate-for-woocommerce/includes/class-utilityhouse-release-gate.php",import.meta.url).pathname);
  const trigger=(key:string)=>spawnSync("php",["-r",`define('ABSPATH', __DIR__); define('UTILITYHOUSE_RELEASE_GATE_VERSION','1.2.1'); $actions=array(); $options=array('utilityhouse_release_gate_service_url'=>'https://app.utilityhouse.xyz','utilityhouse_release_gate_store_id'=>'store_aaaa','utilityhouse_release_gate_evidence_current'=>$argv[1],'utilityhouse_release_gate_evidence_key_id'=>'current','utilityhouse_release_gate_evidence_enabled'=>'1'); $captured=null; $scheduled=array(); function add_action($hook,$callback,$priority=10){global $actions;$actions[$hook]=$callback;} function add_filter($hook,$callback){return true;} function add_rewrite_rule($regex,$query,$position){return true;} function get_option($key,$default=''){global $options;return isset($options[$key])?$options[$key]:$default;} function wp_json_encode($v,$f=0){return json_encode($v,$f);} function wp_generate_password($n,$a=false,$b=false){return 'nonce_e2e_0000000001';} function wc_get_products($args){return array(1);} function wp_parse_url($v){return parse_url($v);} function untrailingslashit($s){return rtrim($s,'/');} function wp_remote_post($url,$args){global $captured;$captured=array('url'=>$url,'args'=>$args);return array('response'=>array('code'=>201));} function is_wp_error($r){return false;} function wp_remote_retrieve_response_code($r){return $r['response']['code'];} function wp_next_scheduled($hook){return false;} function wp_schedule_event($time,$recurrence,$hook){global $scheduled;$scheduled[]=array($time,$recurrence,$hook);return true;} require ${pluginPath}; UtilityHouse_Release_Gate::init(); UtilityHouse_Release_Gate::activate(); call_user_func($actions['utilityhouse_release_gate_evidence']); global $captured,$scheduled; echo json_encode(array('captured'=>$captured,'scheduled'=>$scheduled));`,key],{encoding:"utf8"});
  const php=trigger("a".repeat(64));assert.equal(php.status,0,php.stderr);const phpPost=JSON.parse(php.stdout) as {captured:{url:string;args:{headers:Record<string,string>;body:string}};scheduled:unknown[]};assert.equal(phpPost.captured.url,"https://app.utilityhouse.xyz/api/v2/release-evidence");assert.equal(phpPost.scheduled.length,0,"activation never creates the aggregate schedule");assert.doesNotMatch(phpPost.captured.args.body,/utilityhouse_release_gate_evidence_current|customer|order|payment/i);const phpEnvelope={evidence:JSON.parse(phpPost.captured.args.body) as Record<string,unknown>,signature:phpPost.captured.args.headers["X-UtilityHouse-Release-Gate-Signature"]};
  // The same registered trigger with the authenticated connection-bundle key is accepted.
  const signed=trigger(derived);assert.equal(signed.status,0,signed.stderr);const signedPost=JSON.parse(signed.stdout) as {captured:{args:{headers:Record<string,string>;body:string}}};const envelope={evidence:JSON.parse(signedPost.captured.args.body) as Record<string,unknown>,signature:signedPost.captured.args.headers["X-UtilityHouse-Release-Gate-Signature"]};
  assert.notEqual(phpEnvelope.signature,envelope.signature);
  const body=JSON.stringify(envelope.evidence);const ingest=await worker.fetch(request("/api/v2/release-evidence",{method:"POST",headers:{"content-type":"application/json","x-utilityhouse-release-gate-signature":envelope.signature},body}),env as never);assert.equal(ingest.status,201);assert.equal((await json(ingest)).code,"ACCEPTED");
  const invalidKey=await worker.fetch(request("/api/v2/release-evidence",{method:"POST",headers:{"content-type":"application/json","x-utilityhouse-release-gate-signature":phpEnvelope.signature},body:JSON.stringify(phpEnvelope.evidence)}),env as never);assert.equal(invalidKey.status,403);
  const replay=await worker.fetch(request("/api/v2/release-evidence",{method:"POST",headers:{"content-type":"application/json","x-utilityhouse-release-gate-signature":envelope.signature},body}),env as never);assert.equal(replay.status,409);
  assert.equal((raw.prepare("SELECT COUNT(*) n FROM release_gate_evidence_commits WHERE state='COMMITTED'").get() as {n:number}).n,1,"replay cannot replace the prior generation");
  const bad=await worker.fetch(request("/api/v2/release-evidence",{method:"POST",headers:{"content-type":"application/json","x-utilityhouse-release-gate-signature":"0".repeat(64)},body}),env as never);assert.equal(bad.status,403);
  const hostile={...(envelope.evidence as object),checks:{woo_rollup:{state:"PASS",count:1,customer_email:"buyer@example.test"}}};const hostileRes=await worker.fetch(request("/api/v2/release-evidence",{method:"POST",headers:{"content-type":"application/json","x-utilityhouse-release-gate-signature":await hmac(derived,canonicalPluginEvidence(hostile as never))},body:JSON.stringify(hostile)}),env as never);assert.equal(hostileRes.status,400);
  const makeEvidence=async(nonce:string,keyId:"current"|"previous",generatedAt:string,expiresAt:string,storeId="store_aaaa",state:"PASS"|"FAIL"="PASS")=>{const unsigned={schema_version:"2026-09-06" as const,store_id:storeId,generated_at:generatedAt,expires_at:expiresAt,nonce,key_id:keyId,collector_version:"0.1.0",families:["woo"],checks:{woo_rollup:{state,count:1}}};const packet={...unsigned,digest:await pluginEvidenceDigest(unsigned)};const root=keyId==="current"?"current-root-key":"previous-root-key";const k=await hmac(root,`agentready-plugin-evidence:${storeId}:${keyId}`);return{packet,signature:await hmac(k,canonicalPluginEvidence(packet))};};
  const iso=new Date().toISOString();const previous=await makeEvidence("nonce_previous_000001","previous",iso,new Date(Date.now()+300000).toISOString());const previousRes=await worker.fetch(request("/api/v2/release-evidence",{method:"POST",headers:{"content-type":"application/json","x-agentready-evidence-signature":previous.signature},body:JSON.stringify(previous.packet)}),env as never);assert.equal(previousRes.status,201,"the former header and previous key remain valid during grace");
  const expiredGrace=await makeEvidence("nonce_previous_expired","previous",iso,new Date(Date.now()+300000).toISOString());const expiredGraceRes=await worker.fetch(request("/api/v2/release-evidence",{method:"POST",headers:{"content-type":"application/json","x-utilityhouse-release-gate-signature":expiredGrace.signature},body:JSON.stringify(expiredGrace.packet)}),{...env,RELEASE_EVIDENCE_PREVIOUS_KEY_EXPIRES_AT:new Date(Date.now()-1).toISOString()} as never);assert.equal(expiredGraceRes.status,403,"expired previous key is fail-closed");
  const future=await makeEvidence("nonce_future_000001","current",new Date(Date.now()+120000).toISOString(),new Date(Date.now()+300000).toISOString());const futureRes=await worker.fetch(request("/api/v2/release-evidence",{method:"POST",headers:{"content-type":"application/json","x-utilityhouse-release-gate-signature":future.signature},body:JSON.stringify(future.packet)}),env as never);assert.equal(futureRes.status,400);
  const expired=await makeEvidence("nonce_expired_00001","current",new Date(Date.now()-600000).toISOString(),new Date(Date.now()-1).toISOString());const expiredRes=await worker.fetch(request("/api/v2/release-evidence",{method:"POST",headers:{"content-type":"application/json","x-utilityhouse-release-gate-signature":expired.signature},body:JSON.stringify(expired.packet)}),env as never);assert.equal(expiredRes.status,400);
  const crossStore=await makeEvidence("nonce_cross_store_1","current",iso,new Date(Date.now()+300000).toISOString(),"store_bbbb");crossStore.signature=await hmac(derived,canonicalPluginEvidence(crossStore.packet));const crossStoreRes=await worker.fetch(request("/api/v2/release-evidence",{method:"POST",headers:{"content-type":"application/json","x-utilityhouse-release-gate-signature":crossStore.signature},body:JSON.stringify(crossStore.packet)}),env as never);assert.equal(crossStoreRes.status,403);
  const mime=await worker.fetch(request("/api/v2/release-evidence",{method:"POST",headers:{"content-type":"text/plain"},body}),env as never);assert.equal(mime.status,415);const oversized=await worker.fetch(request("/api/v2/release-evidence",{method:"POST",headers:{"content-type":"application/json"},body:"x".repeat(16385)}),env as never);assert.equal(oversized.status,413);
  const evidenceRows=raw.prepare("SELECT safe_packet_json FROM release_gate_evidence_commits WHERE state='COMMITTED'").all() as Array<{safe_packet_json:string}>;assert.equal(evidenceRows.length,2,"the replay did not replace the original generation");for(const row of evidenceRows)assert.doesNotMatch(row.safe_packet_json,/(buyer@example|secret|authorization|raw)/i);

  const created=await worker.fetch(request("/api/v2/release-api-tokens",{method:"POST",headers:{...cookie,"content-type":"application/json"},body:JSON.stringify({name:"e2e",scopes:["release:start","release:read","release:claim"],store_id:"store_aaaa"})}),env as never);assert.equal(created.status,201);const createdPayload=await json(created);const token=String(createdPayload.token);const tokenId=String((createdPayload.token_metadata as Record<string,unknown>).id);assert.match(token,/^arw_rg_/);const listed=await worker.fetch(request("/api/v2/release-api-tokens",{headers:cookie}),env as never);assert.doesNotMatch(await listed.text(),new RegExp(token));
  const challenge=new ReleaseGateStore(app);const issued=await challenge.createChallenge("store_aaaa","account_a");assert.equal(await challenge.verifyChallenge(issued.id,"store_aaaa","account_a",issued.challenge,await hmac(ownershipKey,issued.challenge),"ownership-root-key"),true);
  const rpc=async(method:string,params:Record<string,unknown>,id:number)=>{const r=await worker.fetch(request("/mcp",{method:"POST",headers:{authorization:`Bearer ${token}`,"content-type":"application/json"},body:JSON.stringify({jsonrpc:"2.0",id,method,params})}),env as never);return await json(r);};
  const inventory=await rpc("tools/list",{},1);const listedTools=((inventory.result as Record<string,unknown>).tools) as Array<{name:string;outputSchema:unknown}>;const tools=listedTools.map(x=>x.name);assert.deepEqual(tools.slice(-3),["start_woo_release_verification","get_woo_release_verification","claim_woo_release_result"]);const outputSchema=new Map(listedTools.map(t=>[t.name,t.outputSchema]));
  const cross=await rpc("tools/call",{name:"start_woo_release_verification",arguments:{store_id:"store_bbbb",mode:"owned-safe-active",requested_families:["woo"],idempotency_key:"cross_tenant_key_0001"}},2);assert.match(JSON.stringify(cross),/AUTH_REQUIRED/);
  const started=await rpc("tools/call",{name:"start_woo_release_verification",arguments:{store_id:"store_aaaa",mode:"owned-safe-active",requested_families:["woo"],idempotency_key:"e2e_start_key_0000001"}},3);const startedText=String((((started.result as Record<string,unknown>).content as Array<{text:string}>)[0]).text);const startedValue=JSON.parse(startedText);assert.equal(schemaMatches(outputSchema.get("start_woo_release_verification"),startedValue),true);const runId=String((startedValue as Record<string,unknown>).run_id);assert.ok(runId);const got=await rpc("tools/call",{name:"get_woo_release_verification",arguments:{run_id:runId}},4);assert.match(JSON.stringify(got),/ACCEPTED/);const getValue=JSON.parse(String((((got.result as Record<string,unknown>).content as Array<{text:string}>)[0]).text));assert.equal(schemaMatches(outputSchema.get("get_woo_release_verification"),getValue),true);
  const restClaim=()=>worker.fetch(request(`/api/v2/acceptance-runs/${runId}/claim-result`,{method:"POST",headers:cookie}),env as never).then(json);const mcpClaim=()=>rpc("tools/call",{name:"claim_woo_release_result",arguments:{run_id:runId}},5);
  const claims=await Promise.all(Array.from({length:10},(_,i)=>i%2?mcpClaim():restClaim()));const eligible=claims.filter(value=>JSON.stringify(value).includes("ELIGIBLE_ON_FIRST_DELIVERY"));assert.equal(eligible.length,1);assert.equal((raw.prepare("SELECT COUNT(*) n FROM release_gate_billable_claims").get() as {n:number}).n,1);assert.equal((raw.prepare("SELECT COUNT(*) n FROM financial_operations").get() as {n:number}).n,0);
  const again=await mcpClaim();assert.match(JSON.stringify(again),/REPLAY/);assert.match(JSON.stringify(again),/NOT_BILLABLE/);const claimValue=JSON.parse(String((((again.result as Record<string,unknown>).content as Array<{text:string}>)[0]).text));assert.equal(schemaMatches(outputSchema.get("claim_woo_release_result"),claimValue),true);
  const failing=await makeEvidence("nonce_fail_0000000001","current",new Date().toISOString(),new Date(Date.now()+300000).toISOString(),"store_aaaa","FAIL");const failingIngest=await worker.fetch(request("/api/v2/release-evidence",{method:"POST",headers:{"content-type":"application/json","x-utilityhouse-release-gate-signature":failing.signature},body:JSON.stringify(failing.packet)}),env as never);assert.equal(failingIngest.status,201);const rejected=await rpc("tools/call",{name:"start_woo_release_verification",arguments:{store_id:"store_aaaa",mode:"owned-safe-active",requested_families:["woo"],idempotency_key:"e2e_reject_key_000001"}},6);const rejectedId=String((JSON.parse(String((((rejected.result as Record<string,unknown>).content as Array<{text:string}>)[0]).text)) as Record<string,unknown>).run_id);const rejectedGet=await rpc("tools/call",{name:"get_woo_release_verification",arguments:{run_id:rejectedId}},7);assert.match(JSON.stringify(rejectedGet),/REJECTED/);
  const concurrent=await makeEvidence("nonce_concurrent_0001","current",new Date().toISOString(),new Date(Date.now()+300000).toISOString());const simultaneous=await Promise.all(Array.from({length:10},()=>worker.fetch(request("/api/v2/release-evidence",{method:"POST",headers:{"content-type":"application/json","x-utilityhouse-release-gate-signature":concurrent.signature},body:JSON.stringify(concurrent.packet)}),env as never)));assert.equal(simultaneous.filter(r=>r.status===201).length,1);assert.equal(simultaneous.filter(r=>r.status===409).length,9);assert.equal((raw.prepare("SELECT COUNT(*) n FROM release_gate_evidence_commits WHERE nonce='nonce_concurrent_0001' AND state='COMMITTED'").get() as {n:number}).n,1);assert.equal((raw.prepare("SELECT COUNT(*) n FROM release_gate_active_evidence WHERE store_id='store_aaaa'").get() as {n:number}).n,1);assert.equal(fetchCalls,0,"signed evidence workflow made no URL fetches");
  const rotated=await worker.fetch(request(`/api/v2/release-api-tokens/${tokenId}/rotate`,{method:"POST",headers:cookie}),env as never);assert.equal(rotated.status,201);const rotatedPayload=await json(rotated);const replacement=String(rotatedPayload.token);const replacementId=String((rotatedPayload.token_metadata as Record<string,unknown>).id);const oldGet=await worker.fetch(request("/mcp",{method:"POST",headers:{authorization:`Bearer ${token}`,"content-type":"application/json"},body:JSON.stringify({jsonrpc:"2.0",id:9,method:"tools/call",params:{name:"get_woo_release_verification",arguments:{run_id:runId}}})}),env as never);assert.match(await oldGet.text(),/AUTH_REQUIRED/);const revoked=await worker.fetch(request(`/api/v2/release-api-tokens/${replacementId}`,{method:"DELETE",headers:cookie}),env as never);assert.equal(revoked.status,204);const replacementGet=await worker.fetch(request("/mcp",{method:"POST",headers:{authorization:`Bearer ${replacement}`,"content-type":"application/json"},body:JSON.stringify({jsonrpc:"2.0",id:10,method:"tools/call",params:{name:"get_woo_release_verification",arguments:{run_id:runId}}})}),env as never);assert.match(await replacementGet.text(),/AUTH_REQUIRED/);
});
