import type { EvidencePacket, ReleaseCheck, ReleaseFamily, ReleaseState, ReasonCode } from "./types.ts";
import type { ProtocolBundle } from "./types.ts";

const CHECK_EVIDENCE: Record<string, readonly string[]> = {
  target:["safe"],"woo-store-api":["status","sample_count","catalogue_total","page_count","mime_valid"],"robots-crawler-policy":["search","user_fetch","training"],"product-jsonld":["sampled_pages","product_pages","offer_pages","page_count"],"mcp-discovery":["status","mime_valid"],"ucp-discovery":["status","mime_valid"],"acp-discovery":["status","mime_valid"],"mcp-initialize":["protocol_version"],"mcp-ping":["ok"],"mcp-tools-list":["tool_count"],"mcp-tools-call":["ok"],"mcp-tool-contract":["reviewed_tools"],"ucp-profile":["capability_count","version_matches"],"acp-profile":["api_declared","feed_declared","version_matches"],"offer-consistency":["sampled_identifiers","conflicting_identifiers","source_count"],"active-flow-barrier":["allowed"],"active-flow":["authorized"],"plugin-woo-rollup":["count"],"plugin-robots-rollup":["count"],"plugin-jsonld-rollup":["count"],"plugin-mcp-rollup":["count"],"plugin-ucp-rollup":["count"],"plugin-acp-rollup":["count"],forbidden:[],
};
const ID=new Set(Object.keys(CHECK_EVIDENCE));
const SENSITIVE_VALUE=/(?:https?:\/\/|\b(?:[\w.+-]+@[\w.-]+\.[a-z]{2,})\b|\b(?:token|secret|password|authorization|cookie|bearer|wallet|0x[a-f0-9]{20,}|order[_ -]?id|payment[_ -]?id|customer[_ -]?id|address|phone|ip(?:v[46])?)\b)/i;
const REASON_CODES=new Set<ReasonCode>(["TARGET_INVALID","TARGET_PRIVATE","TARGET_REDIRECT_UNSAFE","TARGET_DNS_REBIND","TARGET_TIMEOUT","TARGET_BYTES_EXCEEDED","TARGET_RATE_LIMITED","ROBOTS_BLOCKED","WOO_API_UNAVAILABLE","WOO_SAMPLE_EMPTY","JSONLD_PRODUCT_MISSING","JSONLD_OFFER_MISSING","DISCOVERY_UNDECLARED","PROTOCOL_VERSION_UNSUPPORTED","PROTOCOL_SCHEMA_INVALID","MCP_INITIALIZE_FAILED","MCP_TOOLS_LIST_FAILED","MCP_TOOL_ANNOTATION_UNSAFE","MCP_TOOL_CALL_FAILED","UCP_PROFILE_INVALID","ACP_PROFILE_INVALID","CROSS_SURFACE_CONFLICT","OWNERSHIP_REQUIRED","OWNERSHIP_EXPIRED","ACTIVE_FLOW_FORBIDDEN","EVIDENCE_INVALID","INFRA_PERSISTENCE_FAILED","UNMEASURED_SOURCE","CONNECTION_UNVERIFIABLE","INVALID_MIME","INVALID_JSON","PAGINATION_DRIFT","CANCELED_BY_CALLER"]);
export class UnsafeEvidenceError extends Error { constructor(){super("EVIDENCE_INVALID");} }
function canonical(value:unknown):string {if(Array.isArray(value))return`[${value.map(canonical).join(",")}]`;if(value&&typeof value==="object")return`{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${JSON.stringify(k)}:${canonical(v)}`).join(",")}}`;return JSON.stringify(value);}
export async function sha256(value:string):Promise<string>{return[...new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value)))].map(v=>v.toString(16).padStart(2,"0")).join("");}
function validValue(value:unknown):value is string|number|boolean|null{return(typeof value==="string"&&value.length<=80&&!SENSITIVE_VALUE.test(value))||(typeof value==="number"&&Number.isFinite(value))||typeof value==="boolean"||value===null;}
export function validateCheck(check:ReleaseCheck):void{if(!ID.has(check.id)||!["woo","robots","jsonld","mcp","ucp","acp"].includes(check.family)||!["PASS","FAIL","BLOCKED","NOT_APPLICABLE","UNMEASURED"].includes(check.state))throw new UnsafeEvidenceError();if(check.reasonCode&&!REASON_CODES.has(check.reasonCode))throw new UnsafeEvidenceError();const allowed=new Set(CHECK_EVIDENCE[check.id]);for(const[key,value]of Object.entries(check.evidence))if(!allowed.has(key)||!validValue(value))throw new UnsafeEvidenceError();}
export function safeChecks(checks:readonly ReleaseCheck[]):ReleaseCheck[]{checks.forEach(validateCheck);return checks.map(c=>({id:c.id,family:c.family,state:c.state,...(c.reasonCode?{reasonCode:c.reasonCode}:{}),evidence:{...c.evidence}}));}
export async function createEvidencePacket(runId:string,state:ReleaseState,checks:ReleaseCheck[],bundles:ProtocolBundle[],requested:ReleaseFamily[],sampleSize:number,catalogueTotal:number|null,unknowns:ReasonCode[]):Promise<EvidencePacket>{if(!/^[-_a-zA-Z0-9]{8,100}$/.test(runId)||!unknowns.every(x=>REASON_CODES.has(x))||!Number.isSafeInteger(sampleSize)||sampleSize<0||(catalogueTotal!==null&&(!Number.isSafeInteger(catalogueTotal)||catalogueTotal<0)))throw new UnsafeEvidenceError();const safe=safeChecks(checks);const packet={schema_version:"2026-09-06"as const,run_id:runId,state,checks:safe,protocol_bundles:bundles.map(({family,release,sourceSha256,vectorSha256,builtAt})=>({family,release,sourceSha256,vectorSha256,builtAt})),coverage:{requested_families:requested,completed_families:[...new Set(safe.map(c=>c.family))],sample_size:sampleSize,catalogue_total:catalogueTotal},unknowns,observed_at:new Date().toISOString()};const digest=await sha256(canonical(packet));const result={...packet,digest};if(!evidenceIsSafe(result))throw new UnsafeEvidenceError();return result;}
export function evidenceIsSafe(packet:EvidencePacket):boolean{try{if(JSON.stringify(packet).length>64_000||!packet.unknowns.every(x=>REASON_CODES.has(x)))return false;packet.checks.forEach(validateCheck);return!SENSITIVE_VALUE.test(JSON.stringify(packet));}catch{return false;}}
