import { PRELIGHT_INPUT_SCHEMA, ACCEPTANCE_INPUT_SCHEMA, parseAcceptanceRunInput, parsePreflightInput } from "./schemas.ts";
import { runPreflight, type PreflightDependencies } from "./preflight.ts";
import { authenticateReleaseToken } from "./apiTokens.ts";
import { ReleaseGateStore } from "./store.ts";
import { validatePluginEvidence } from "./pluginEvidence.ts";
import { evidenceCoversFamilies } from "./signedEvidence.ts";
import type { AppStore } from "../core/appStore.ts";
import type { McpTool } from "../core/mcpRpc.ts";

const RUN_ID_SCHEMA={type:"object",additionalProperties:false,required:["run_id"],properties:{run_id:{type:"string",minLength:8,maxLength:100,description:"Release Gate run identifier returned by start_woo_release_verification. It must belong to the authenticated account; never substitute a store URL, credential, or customer value."}}};
const CODES=["AUTH_REQUIRED","STORE_NOT_FOUND","OWNERSHIP_REQUIRED","WORKFLOW_UNAVAILABLE","WORKFLOW_DISPATCH_FAILED","INVALID_INPUT","RUN_NOT_FOUND","RESULT_NOT_READY","EVIDENCE_REQUIRED"];
const FAILURE_SCHEMA={type:"object",additionalProperties:false,required:["code"],properties:{code:{type:"string",enum:CODES},state:{type:"string",enum:["BLOCKED","UNMEASURED"]},settlement:{const:"disabled"}}};
// A code-only error must be structurally distinct from EVIDENCE_REQUIRED,
// whose state is part of the contract.  Keeping the branches disjoint makes
// this a real `oneOf`, not a permissive union in disguise.
const BARE_FAILURE_SCHEMA={type:"object",additionalProperties:false,required:["code"],properties:{code:{type:"string",enum:CODES}}};
const START_SCHEMA={type:"object",oneOf:[{type:"object",additionalProperties:false,required:["run_id","state","settlement"],properties:{run_id:{type:"string",minLength:8,maxLength:100},state:{type:"string",enum:["QUEUED","RUNNING","RETRYING","TERMINAL","CANCELED"]},settlement:{const:"disabled"}}},{type:"object",additionalProperties:false,required:["code","state","settlement"],properties:{code:{const:"EVIDENCE_REQUIRED"},state:{type:"string",enum:["BLOCKED","UNMEASURED"]},settlement:{const:"disabled"}}},BARE_FAILURE_SCHEMA]};
const GET_SCHEMA={type:"object",oneOf:[{type:"object",additionalProperties:false,required:["run_id","state","terminal_state","evidence_digest"],properties:{run_id:{type:"string",minLength:8,maxLength:100},state:{type:"string",enum:["QUEUED","RUNNING","RETRYING","TERMINAL","CANCELED"]},terminal_state:{type:["string","null"]},evidence_digest:{type:["string","null"]}}},FAILURE_SCHEMA]};
const SAFE_EVIDENCE_SCHEMA={type:"object",additionalProperties:false,properties:{safe:{type:"boolean"},status:{type:"number"},sample_count:{type:"number"},catalogue_total:{type:["number","null"]},page_count:{type:"number"},mime_valid:{type:"boolean"},search:{type:"boolean"},user_fetch:{type:"boolean"},training:{type:"boolean"},sampled_pages:{type:"number"},product_pages:{type:"number"},offer_pages:{type:"number"},protocol_version:{type:"string"},ok:{type:"boolean"},tool_count:{type:"number"},reviewed_tools:{type:"number"},capability_count:{type:"number"},version_matches:{type:"boolean"},api_declared:{type:"boolean"},feed_declared:{type:"boolean"},sampled_identifiers:{type:"number"},conflicting_identifiers:{type:"number"},source_count:{type:"number"},allowed:{type:"boolean"},authorized:{type:"boolean"},count:{type:"number"}}};
const FAMILIES=["woo","robots","jsonld","mcp","ucp","acp"];
const REASON_CODES=["TARGET_INVALID","TARGET_PRIVATE","TARGET_REDIRECT_UNSAFE","TARGET_DNS_REBIND","TARGET_TIMEOUT","TARGET_BYTES_EXCEEDED","TARGET_RATE_LIMITED","ROBOTS_BLOCKED","WOO_API_UNAVAILABLE","WOO_SAMPLE_EMPTY","JSONLD_PRODUCT_MISSING","JSONLD_OFFER_MISSING","DISCOVERY_UNDECLARED","PROTOCOL_VERSION_UNSUPPORTED","PROTOCOL_SCHEMA_INVALID","MCP_INITIALIZE_FAILED","MCP_TOOLS_LIST_FAILED","MCP_TOOL_ANNOTATION_UNSAFE","MCP_TOOL_CALL_FAILED","UCP_PROFILE_INVALID","ACP_PROFILE_INVALID","CROSS_SURFACE_CONFLICT","OWNERSHIP_REQUIRED","OWNERSHIP_EXPIRED","ACTIVE_FLOW_FORBIDDEN","EVIDENCE_INVALID","INFRA_PERSISTENCE_FAILED","UNMEASURED_SOURCE","CONNECTION_UNVERIFIABLE","INVALID_MIME","INVALID_JSON","PAGINATION_DRIFT","CANCELED_BY_CALLER"];
const FAMILY_ARRAY={type:"array",items:{type:"string",enum:FAMILIES}};
const BUNDLE_SCHEMA={type:"object",additionalProperties:false,required:["family","release","sourceSha256","vectorSha256","builtAt"],properties:{family:{type:"string",enum:["mcp","ucp","acp"]},release:{type:"string",minLength:1,maxLength:100},sourceSha256:{type:"string",pattern:"^[a-f0-9]{64}$"},vectorSha256:{type:"string",pattern:"^[a-f0-9]{64}$"},builtAt:{type:"string",format:"date-time"}}};
const PACKET_SCHEMA={type:"object",additionalProperties:false,required:["schema_version","run_id","state","checks","protocol_bundles","coverage","unknowns","observed_at","digest"],properties:{schema_version:{const:"2026-09-06"},run_id:{type:"string",pattern:"^[A-Za-z0-9_-]{8,100}$"},state:{type:"string",enum:["ACCEPTED","REJECTED","PARTIAL","BLOCKED","UNMEASURED","INFRA_ERROR","CANCELED"]},checks:{type:"array",items:{type:"object",additionalProperties:false,required:["id","family","state","evidence"],properties:{id:{type:"string",minLength:1,maxLength:100},family:{type:"string",enum:FAMILIES},state:{type:"string",enum:["PASS","FAIL","BLOCKED","NOT_APPLICABLE","UNMEASURED"]},reasonCode:{type:"string",enum:REASON_CODES},evidence:SAFE_EVIDENCE_SCHEMA}}},protocol_bundles:{type:"array",items:BUNDLE_SCHEMA},coverage:{type:"object",additionalProperties:false,required:["requested_families","completed_families","sample_size","catalogue_total"],properties:{requested_families:FAMILY_ARRAY,completed_families:FAMILY_ARRAY,sample_size:{type:"integer",minimum:0},catalogue_total:{type:["integer","null"],minimum:0}}},unknowns:{type:"array",items:{type:"string",enum:REASON_CODES}},observed_at:{type:"string",format:"date-time"},digest:{type:"string",pattern:"^[a-f0-9]{64}$"}}};
const CLAIM_SCHEMA={type:"object",oneOf:[{type:"object",additionalProperties:false,required:["packet","delivery","billable_eligibility","settlement"],properties:{packet:{oneOf:[PACKET_SCHEMA,{type:"null"}]},delivery:{type:"string",enum:["FIRST","REPLAY"]},billable_eligibility:{type:"string",enum:["ELIGIBLE_ON_FIRST_DELIVERY","NOT_BILLABLE"]},settlement:{const:"disabled"}}},FAILURE_SCHEMA]};
const PREFLIGHT_SCHEMA={type:"object",additionalProperties:false,required:["kind","state","store_origin","requested_families","sample_seed","sample_size","catalogue_total","checks","protocol_bundles","observed_at","unknowns"],properties:{kind:{const:"preflight"},state:{type:"string",enum:["ACCEPTED","REJECTED","PARTIAL","BLOCKED","UNMEASURED"]},store_origin:{type:"string",format:"uri"},requested_families:FAMILY_ARRAY,sample_seed:{type:"string"},sample_size:{type:"integer",minimum:0},catalogue_total:{type:["integer","null"],minimum:0},checks:{type:"array",items:{type:"object",additionalProperties:false,required:["id","family","state","evidence"],properties:{id:{type:"string"},family:{type:"string",enum:FAMILIES},state:{type:"string",enum:["PASS","FAIL","BLOCKED","NOT_APPLICABLE","UNMEASURED"]},reasonCode:{type:"string",enum:REASON_CODES},evidence:{type:"object"}}}},protocol_bundles:{type:"array",items:{type:"object"}},observed_at:{type:"string",format:"date-time"},unknowns:{type:"array",items:{type:"string",enum:REASON_CODES}}}};
export interface AuthenticatedReleaseGateDeps { app:AppStore; workflow?:{create(input:{params:{runId:string}}):Promise<unknown>}; }
function id(args:Record<string,unknown>):string|null{return typeof args.run_id==="string"&&/^[A-Za-z0-9_-]{8,100}$/.test(args.run_id)?args.run_id:null;}
function reply(value:unknown){return{ok:true as const,text:JSON.stringify(value)};}
function failure(code:string){return{ok:false as const,text:JSON.stringify({code})};}

/** Free discovery stays separate; stateful paid tools require an account API
 * token passed through the MCP Authorization context, never tool arguments. */
export function releaseGateMcpTools(deps: PreflightDependencies = {}, authenticated?:AuthenticatedReleaseGateDeps): McpTool[] {
  const free:McpTool={name:"preflight_woo_store",description:"Use ONLY before a specific WooCommerce update or release when you need protocol-family evidence. Do NOT use it for a general score or fix list; use scan_woo_store_readiness for that. Inspect selected public WooCommerce and agent-protocol surfaces and return per-family PASS, FAIL, BLOCKED or UNMEASURED evidence. It changes nothing, is free, and BLOCKED or UNMEASURED is an abstention rather than a finding about the store.",inputSchema:PRELIGHT_INPUT_SCHEMA,outputSchema:PREFLIGHT_SCHEMA,annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:true},async run(args){try{return reply(await runPreflight(parsePreflightInput(args),deps));}catch{return failure("INVALID_INPUT");}}};
  if(!authenticated)return[free];
  const gate=new ReleaseGateStore(authenticated.app);
  return [free,
    {name:"start_woo_release_verification",description:"Start an ownership-authorized Release Gate run. Requires a bearer token with release:start.",inputSchema:ACCEPTANCE_INPUT_SCHEMA,outputSchema:START_SCHEMA,annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:true},async run(args,context){
      try{const input=parseAcceptanceRunInput(args);const principal=await authenticateReleaseToken(authenticated.app,context?.authorization,"release:start",input.store_id);if(!principal)return failure("AUTH_REQUIRED");const store=await authenticated.app.getStoreForUser(input.store_id,principal.accountId);if(!store)return failure("STORE_NOT_FOUND");if(!await authenticated.app.hasVerifiedReleaseOwnership(store.id,principal.accountId))return failure("OWNERSHIP_REQUIRED");const generation=await authenticated.app.getActivePluginEvidence(store.id,principal.accountId);if(!generation)return reply({code:"EVIDENCE_REQUIRED",state:"BLOCKED",settlement:"disabled"});let packet;try{packet=await validatePluginEvidence(JSON.parse(generation.safePacket));}catch{return reply({code:"EVIDENCE_REQUIRED",state:"UNMEASURED",settlement:"disabled"});}if(packet.digest!==generation.digest||!evidenceCoversFamilies(packet,input.requested_families))return reply({code:"EVIDENCE_REQUIRED",state:"UNMEASURED",settlement:"disabled"});if(!authenticated.workflow)return failure("WORKFLOW_UNAVAILABLE");const run=await gate.createOrGetRun(principal.accountId,input);try{await authenticated.workflow.create({params:{runId:run.id}});}catch{await gate.markDispatchFailed(run);return failure("WORKFLOW_DISPATCH_FAILED");}return reply({run_id:run.id,state:run.state,settlement:"disabled"});}catch{return failure("INVALID_INPUT");}
    }},
    {name:"get_woo_release_verification",description:"Get a Release Gate run owned by the bearer token account. Requires release:read.",inputSchema:RUN_ID_SCHEMA,outputSchema:GET_SCHEMA,annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false},async run(args,context){
      const runId=id(args);if(!runId)return failure("INVALID_INPUT");const principal=await authenticateReleaseToken(authenticated.app,context?.authorization,"release:read");if(!principal)return failure("AUTH_REQUIRED");const run=await gate.getRun(runId,principal.accountId);if(!run||(principal.storeId!==null&&run.storeId!==principal.storeId))return failure("RUN_NOT_FOUND");return reply({run_id:run.id,state:run.state,terminal_state:run.terminalState,evidence_digest:run.evidenceDigest});
    }},
    {name:"claim_woo_release_result",description:"Claim a completed Release Gate result once. Requires release:claim; replay is never billable.",inputSchema:RUN_ID_SCHEMA,outputSchema:CLAIM_SCHEMA,annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false},async run(args,context){
      const runId=id(args);if(!runId)return failure("INVALID_INPUT");const principal=await authenticateReleaseToken(authenticated.app,context?.authorization,"release:claim");if(!principal)return failure("AUTH_REQUIRED");const run=await gate.getRun(runId,principal.accountId);if(!run||(principal.storeId!==null&&run.storeId!==principal.storeId))return failure("RUN_NOT_FOUND");if(run.state!=="TERMINAL")return failure("RESULT_NOT_READY");const claim=await gate.claim(run,"mcp",principal.tokenId);return reply({packet:claim.packet,delivery:claim.firstDelivery?"FIRST":"REPLAY",billable_eligibility:claim.billable?"ELIGIBLE_ON_FIRST_DELIVERY":"NOT_BILLABLE",settlement:"disabled"});
    }}
  ];
}
