import type { FetchLike } from "../core/scan.ts";
import { classify } from "./classifier.ts";
import { bundlesFor } from "./protocolBundles.ts";
import { TargetGuard,TargetGuardError,failClosedResolver,type TargetResolver } from "./targetGuard.ts";
import { verifyMcp, type McpTransport } from "./mcpVerifier.ts";
import { verifyUcpProfile } from "./ucpVerifier.ts";
import { verifyAcpProfile } from "./acpVerifier.ts";
import type { CheckState,PreflightInput,PreflightResult,ReasonCode,ReleaseCheck,ReleaseFamily } from "./types.ts";
export interface PreflightDependencies{fetchImpl?:FetchLike;resolver?:TargetResolver;connectionBinding?:"verified";mcpTransport?:McpTransport;now?:()=>Date;}
type Product={id?:number;permalink?:string}; const c=(id:string,family:ReleaseFamily,state:CheckState,reasonCode:ReleaseCheck["reasonCode"],evidence:ReleaseCheck["evidence"]):ReleaseCheck=>({id,family,state,...(reasonCode?{reasonCode}:{}),evidence});
function robotsAllows(text:string,agent:string,path="/"):boolean{type Group={agents:string[];rules:Array<{kind:"allow"|"disallow";path:string}>};const groups:Group[]=[];let current:Group|null=null;for(const raw of text.split(/\r?\n/)){const line=raw.replace(/#.*/,"").trim();if(!line)continue;const i=line.indexOf(":");if(i<0)continue;const key=line.slice(0,i).trim().toLowerCase(),value=line.slice(i+1).trim();if(key==="user-agent"){if(!current||current.rules.length)groups.push(current={agents:[],rules:[]});current.agents.push(value.toLowerCase());}else if(current&&(key==="allow"||key==="disallow"))current.rules.push({kind:key,path:value});}const matches=groups.filter(g=>g.agents.includes(agent.toLowerCase())||g.agents.includes("*"));const exact=matches.filter(g=>g.agents.includes(agent.toLowerCase()));const selected=exact.length?exact:matches;let best:{length:number;allow:boolean}|null=null;for(const g of selected)for(const rule of g.rules){const anchored=rule.path.endsWith("$"),source=rule.path.replace(/\$$/,"").split("*").map(x=>x.replace(/[.+?^{}()|[\]\\]/g,"\\$&")).join(".*"),hit=rule.path&&new RegExp(`^${source}${anchored?"$":""}`).test(path);if(hit&&(!best||rule.path.length>best.length||rule.path.length===best.length&&rule.kind==="allow"))best={length:rule.path.length,allow:rule.kind==="allow"};}return best?.allow??true;}
function seed(origin:string):number{let value=2166136261;for(const ch of origin)value=Math.imul(value^ch.charCodeAt(0),16777619);return value>>>0;}
function samplePages(total:number,origin:string,size=8):number[]{const take=Math.min(total,size),out=new Set<number>();let state=seed(origin);while(out.size<take){state=(Math.imul(state,1664525)+1013904223)>>>0;out.add(state%total+1);}return[...out].sort((a,b)=>a-b);}
function jsonLd(html:string):{product:boolean;offer:boolean}{const scripts=[...html.matchAll(/<script\b[^>]*\btype\s*=\s*["']application\/ld\+json["'][^>]*>([\s\S]{0,262144}?)<\/script>/gi)].map(m=>m[1]);let product=false,offer=false;const walk=(x:unknown,depth=0)=>{if(depth>20||!x)return;if(Array.isArray(x)){x.slice(0,200).forEach(v=>walk(v,depth+1));return;}if(typeof x!=="object")return;const o=x as Record<string,unknown>,types=Array.isArray(o["@type"])?o["@type"]:[o["@type"]];if(types.includes("Product"))product=true;if(types.includes("Offer"))offer=true;for(const value of Object.values(o))walk(value,depth+1);};for(const script of scripts)try{walk(JSON.parse(script));}catch{/* one malformed block does not hide valid blocks */}return{product,offer};}
const mime=(r:Response)=>/^(application\/(json|ld\+json)|text\/(plain|html))\b/i.test(r.headers.get("content-type")??"");
const reportState=(state:ReturnType<typeof classify>):PreflightResult["state"]=>state==="CANCELED"||state==="INFRA_ERROR"?"BLOCKED":state;
export async function runPreflight(input:PreflightInput,deps:PreflightDependencies={}):Promise<PreflightResult>{const now=deps.now??(()=>new Date()),requested=input.requested_families??["woo","robots","jsonld","mcp","ucp","acp"],guard=new TargetGuard({fetchImpl:deps.fetchImpl??fetch,resolver:deps.resolver??failClosedResolver,connectionBinding:deps.connectionBinding,maxRedirects:3,maxBytes:256_000,timeoutMs:8_000}),checks:ReleaseCheck[]=[],unknowns:ReasonCode[]=[];let origin:URL;try{origin=await guard.validate(input.store_origin);}catch(error){const code=error instanceof TargetGuardError?error.code:"TARGET_INVALID";checks.push(c("target","woo","BLOCKED",code,{safe:false}));return{kind:"preflight",state:"BLOCKED",store_origin:input.store_origin,requested_families:requested,sample_seed:"none",sample_size:0,catalogue_total:null,checks,protocol_bundles:bundlesFor(requested),observed_at:now().toISOString(),unknowns:[code]};}
let total:number|null=null,pages:number[]=[],products:Product[]=[];
if(requested.includes("woo"))try{const api=await guard.text(new URL("/wp-json/wc/store/v1/products?per_page=1&page=1",origin));if(!api.response.ok){checks.push(c("woo-store-api","woo","FAIL","WOO_API_UNAVAILABLE",{status:api.response.status,mime_valid:mime(api.response)}));}else if(!mime(api.response)){checks.push(c("woo-store-api","woo","UNMEASURED","INVALID_MIME",{status:api.response.status,mime_valid:false}));unknowns.push("INVALID_MIME");}else{let first:unknown;try{first=JSON.parse(api.text);}catch{checks.push(c("woo-store-api","woo","UNMEASURED","INVALID_JSON",{status:api.response.status,mime_valid:true}));unknowns.push("INVALID_JSON");first=null;}const header=Number(api.response.headers.get("x-wp-total"));if(Array.isArray(first)&&Number.isSafeInteger(header)&&header>=0){total=header;pages=samplePages(total,origin.origin);for(const page of pages){const got=await guard.text(new URL(`/wp-json/wc/store/v1/products?per_page=1&page=${page}`,origin));if(!got.response.ok||!mime(got.response)){unknowns.push(!mime(got.response)?"INVALID_MIME":"UNMEASURED_SOURCE");continue;}try{const data=JSON.parse(got.text);if(!Array.isArray(data)||data.length!==1){unknowns.push("PAGINATION_DRIFT");continue;}products.push(data[0] as Product);}catch{unknowns.push("INVALID_JSON");}}checks.push(c("woo-store-api","woo",products.length===pages.length?(products.length?"PASS":"FAIL"):"UNMEASURED",products.length===pages.length?(products.length?undefined:"WOO_SAMPLE_EMPTY"):"PAGINATION_DRIFT",{status:api.response.status,sample_count:products.length,catalogue_total:total,page_count:pages.length,mime_valid:true}));}else{checks.push(c("woo-store-api","woo","UNMEASURED","PAGINATION_DRIFT",{status:api.response.status,sample_count:0,catalogue_total:null,page_count:0,mime_valid:true}));unknowns.push("PAGINATION_DRIFT");}}}catch(error){const code=error instanceof TargetGuardError?error.code:"UNMEASURED_SOURCE";checks.push(c("woo-store-api","woo","BLOCKED",code,{status:0,mime_valid:false}));unknowns.push(code);}
if(requested.includes("robots"))try{const r=await guard.text(new URL("/robots.txt",origin));if(!r.response.ok||!mime(r.response)){checks.push(c("robots-crawler-policy","robots","UNMEASURED",!mime(r.response)?"INVALID_MIME":"UNMEASURED_SOURCE",{search:false,user_fetch:false,training:false}));unknowns.push(!mime(r.response)?"INVALID_MIME":"UNMEASURED_SOURCE");}else{const evidence={search:robotsAllows(r.text,"OAI-SearchBot")&&robotsAllows(r.text,"Claude-SearchBot"),user_fetch:robotsAllows(r.text,"Claude-User"),training:robotsAllows(r.text,"GPTBot")&&robotsAllows(r.text,"ClaudeBot")};checks.push(c("robots-crawler-policy","robots",evidence.search&&evidence.user_fetch?"PASS":"FAIL",evidence.search&&evidence.user_fetch?undefined:"ROBOTS_BLOCKED",evidence));}}catch{checks.push(c("robots-crawler-policy","robots","UNMEASURED","UNMEASURED_SOURCE",{search:false,user_fetch:false,training:false}));unknowns.push("UNMEASURED_SOURCE");}
if(requested.includes("jsonld")){let productPass=0,offerPass=0;for(const product of products)try{if(typeof product.permalink!=="string"||new URL(product.permalink).origin!==origin.origin)continue;const page=await guard.text(product.permalink);const schema=jsonLd(page.text);productPass+=Number(schema.product);offerPass+=Number(schema.offer);}catch{unknowns.push("UNMEASURED_SOURCE");}const state:CheckState=products.length&&productPass===products.length&&offerPass===products.length?"PASS":products.length?"FAIL":"UNMEASURED";checks.push(c("product-jsonld","jsonld",state,state==="PASS"?undefined:state==="FAIL"?(productPass<products.length?"JSONLD_PRODUCT_MISSING":"JSONLD_OFFER_MISSING"):"UNMEASURED_SOURCE",{sampled_pages:products.length,product_pages:productPass,offer_pages:offerPass,page_count:pages.length}));}
for(const family of ["mcp","ucp","acp"]as const)if(requested.includes(family))try{const path=family==="mcp"?"/.well-known/mcp.json":family==="ucp"?"/.well-known/ucp":"/.well-known/acp.json",found=await guard.text(new URL(path,origin)),id=`${family}-discovery`as const;if(!found.response.ok){checks.push(c(id,family,"NOT_APPLICABLE","DISCOVERY_UNDECLARED",{status:found.response.status,mime_valid:mime(found.response)}));continue;}if(!mime(found.response)){checks.push(c(id,family,"UNMEASURED","INVALID_MIME",{status:found.response.status,mime_valid:false}));unknowns.push("INVALID_MIME");continue;}let profile:unknown;try{profile=JSON.parse(found.text);}catch{checks.push(c(id,family,"UNMEASURED","INVALID_JSON",{status:found.response.status,mime_valid:true}));unknowns.push("INVALID_JSON");continue;}checks.push(c(id,family,"PASS",undefined,{status:found.response.status,mime_valid:true}));const bundle=bundlesFor([family])[0];if(family==="mcp"){if(!deps.mcpTransport){checks.push(c("mcp-tool-contract","mcp","UNMEASURED","UNMEASURED_SOURCE",{reviewed_tools:0}));unknowns.push("UNMEASURED_SOURCE");}else checks.push(...await verifyMcp(deps.mcpTransport,["release_gate_self_check"]));}else if(family==="ucp")checks.push(...verifyUcpProfile(profile,bundle));else checks.push(...verifyAcpProfile(profile,bundle));}catch(error){const code=error instanceof TargetGuardError?error.code:"UNMEASURED_SOURCE";checks.push(c(`${family}-discovery`,family,"UNMEASURED",code,{status:0,mime_valid:false}));unknowns.push(code);}
const state=classify(checks,requested);return{kind:"preflight",state:reportState(state),store_origin:origin.origin,requested_families:requested,sample_seed:seed(origin.origin).toString(16),sample_size:products.length,catalogue_total:total,checks,protocol_bundles:bundlesFor(requested),observed_at:now().toISOString(),unknowns:[...new Set(unknowns)]};}
