import type { FetchLike } from "../core/scan.ts";
export type TargetFailure="TARGET_INVALID"|"TARGET_PRIVATE"|"TARGET_REDIRECT_UNSAFE"|"TARGET_DNS_REBIND"|"TARGET_TIMEOUT"|"TARGET_BYTES_EXCEEDED"|"TARGET_RATE_LIMITED"|"CONNECTION_UNVERIFIABLE";
export class TargetGuardError extends Error{readonly code:TargetFailure;constructor(code:TargetFailure){super(code);this.code=code;}}
export interface TargetResolver{resolve(hostname:string):Promise<string[]>;}
export interface GuardedFetch{response:Response;url:URL;bytes:number;}
/** Workers cannot bind a fetch socket to a DNS answer. Production callers must
 * provide an adapter that can attest to that binding; otherwise no fetch runs. */
export interface TargetGuardOptions{resolver:TargetResolver;fetchImpl:FetchLike;connectionBinding?:"verified";maxRedirects?:number;timeoutMs?:number;maxBytes?:number;}
const in4=(p:number[],a:number,b=0,c=0,bits=8)=>{let n=0,v=0;for(const x of p)n=(n<<8)|x;for(const x of [a,b,c,0])v=(v<<8)|x;const mask=bits===0?0:(0xffffffff<<(32-bits))>>>0;return ((n>>>0)&mask)===((v>>>0)&mask);};
function v4(ip:string):number[]|null{const p=ip.split(".");if(p.length!==4||p.some(x=>!/^\d{1,3}$/.test(x)))return null;const n=p.map(Number);return n.some(x=>x>255)?null:n;}
function v6Groups(ip:string):number[]|null{let s=ip.toLowerCase();if(s.includes("%"))return null;if(s.startsWith("["))s=s.slice(1,-1);const mapped=s.match(/^(.*:)(\d+\.\d+\.\d+\.\d+)$/);if(mapped){const p=v4(mapped[2]);if(!p)return null;s=`${mapped[1]}${((p[0]<<8)|p[1]).toString(16)}:${((p[2]<<8)|p[3]).toString(16)}`;}const parts=s.split("::");if(parts.length>2)return null;const left=parts[0]?parts[0].split(":"):[];const right=parts.length===2&&parts[1]?parts[1].split(":"):[];if(left.some(x=>!/^[0-9a-f]{1,4}$/.test(x))||right.some(x=>!/^[0-9a-f]{1,4}$/.test(x))||left.length+right.length>8)return null;const fill=Array(Math.max(0,8-left.length-right.length)).fill("0");const all=[...left,...fill,...right];return all.length===8?all.map(x=>parseInt(x,16)):null;}
function prefix6(g:number[],prefix:number,value:number[]):boolean{for(let bit=0;bit<prefix;bit++){const i=Math.floor(bit/16),mask=1<<(15-bit%16);if(Boolean(g[i]&mask)!==Boolean(value[i]&mask))return false;}return true;}
/** IANA special-purpose ranges are deny-by-default; test/documentation ranges
 * intentionally fail so fixtures cannot accidentally normalize unsafe trust. */
export function isPublicAddress(ip:string):boolean{const p=v4(ip);if(p){return ![in4(p,0,0,0,8),in4(p,10,0,0,8),in4(p,100,64,0,10),in4(p,127,0,0,8),in4(p,169,254,0,16),in4(p,172,16,0,12),in4(p,192,0,0,24),in4(p,192,0,2,24),in4(p,192,31,196,24),in4(p,192,52,193,24),in4(p,192,88,99,24),in4(p,192,168,0,16),in4(p,192,175,48,24),in4(p,198,18,0,15),in4(p,198,51,100,24),in4(p,203,0,113,24),in4(p,224,0,0,4),in4(p,240,0,0,4)].some(Boolean);}const g=v6Groups(ip);if(!g)return false;const pfx=(n:number,a:number[])=>prefix6(g,n,a);return ![pfx(128,[0,0,0,0,0,0,0,0]),pfx(128,[0,0,0,0,0,0,0,1]),pfx(96,[0,0,0,0,0,0xffff,0,0]),pfx(10,[0xfe80,0,0,0,0,0,0,0]),pfx(7,[0xfc00,0,0,0,0,0,0,0]),pfx(8,[0xff00,0,0,0,0,0,0,0]),pfx(10,[0xfec0,0,0,0,0,0,0,0]),pfx(32,[0x2001,0xdb8,0,0,0,0,0,0]),pfx(48,[0x2001,0x2,0,0,0,0,0,0]),pfx(64,[0x100,0,0,0,0,0,0,0]),pfx(96,[0x64,0xff9b,0,0,0,0,0,0])].some(Boolean);}
export function canonicalOrigin(raw:string):URL{if(raw.length>2048||/[\u0000-\u001f\u007f\s]/.test(raw))throw new TargetGuardError("TARGET_INVALID");let url:URL;try{url=new URL(raw);}catch{throw new TargetGuardError("TARGET_INVALID");}if(url.protocol!=="https:"||url.username||url.password||url.hash||(url.port&&url.port!=="443")||!url.hostname||/^[\d.]+$/.test(url.hostname)||url.hostname.includes(":"))throw new TargetGuardError("TARGET_INVALID");url.pathname="/";url.search="";return url;}
function safeUrl(raw:string):URL{const origin=canonicalOrigin(raw),parsed=new URL(raw);origin.pathname=parsed.pathname||"/";origin.search=parsed.search;return origin;}
async function publicDns(url:URL,resolver:TargetResolver):Promise<string[]>{const values=await resolver.resolve(url.hostname).catch(()=>[]);if(!values.length||values.some(ip=>!isPublicAddress(ip)))throw new TargetGuardError("TARGET_PRIVATE");return[...new Set(values)].sort();}
export class TargetGuard{private readonly options:TargetGuardOptions;private readonly redirects:number;private readonly timeout:number;private readonly maxBytes:number;constructor(options:TargetGuardOptions){this.options=options;this.redirects=options.maxRedirects??3;this.timeout=options.timeoutMs??8_000;this.maxBytes=options.maxBytes??256_000;}async validate(raw:string):Promise<URL>{const url=canonicalOrigin(raw);await publicDns(url,this.options.resolver);return url;}async fetch(raw:string|URL,init:RequestInit={}):Promise<GuardedFetch>{if(this.options.connectionBinding!=="verified")throw new TargetGuardError("CONNECTION_UNVERIFIABLE");let url=safeUrl(raw.toString());const answers=new Map<string,string>();for(let hop=0;hop<=this.redirects;hop++){const resolved=await publicDns(url,this.options.resolver),prior=answers.get(url.hostname);if(prior&&prior!==resolved.join(","))throw new TargetGuardError("TARGET_DNS_REBIND");answers.set(url.hostname,resolved.join(","));let response:Response;try{response=await this.options.fetchImpl(url.toString(),{...init,redirect:"manual",signal:AbortSignal.timeout(this.timeout)});}catch{throw new TargetGuardError("TARGET_TIMEOUT");}if([301,302,303,307,308].includes(response.status)){const location=response.headers.get("location");if(!location||hop===this.redirects)throw new TargetGuardError("TARGET_REDIRECT_UNSAFE");try{url=safeUrl(new URL(location,url).toString());}catch{throw new TargetGuardError("TARGET_REDIRECT_UNSAFE");}continue;}const declared=Number(response.headers.get("content-length")??"0");if(Number.isFinite(declared)&&declared>this.maxBytes)throw new TargetGuardError("TARGET_BYTES_EXCEEDED");return{response,url,bytes:Math.max(0,declared)};}throw new TargetGuardError("TARGET_REDIRECT_UNSAFE");}async text(raw:string|URL,init:RequestInit={}):Promise<{response:Response;url:URL;text:string}>{const result=await this.fetch(raw,init);if(!result.response.body){return{...result,text:""};}const reader=result.response.body.getReader(),chunks:Uint8Array[]=[];let length=0;try{for(;;){const next=await reader.read();if(next.done)break;length+=next.value.byteLength;if(length>this.maxBytes)throw new TargetGuardError("TARGET_BYTES_EXCEEDED");chunks.push(next.value);}}finally{reader.releaseLock();}const bytes=new Uint8Array(length);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.byteLength;}return{response:result.response,url:result.url,text:new TextDecoder().decode(bytes)};}}
export const failClosedResolver:TargetResolver={async resolve(){return[];}};
