import type { CacheRow, CircuitRow, FinancialOperation, FinancialOperationState,
  ResultEscrowRow, SettlementOutboxRow, SettlementOutboxStatus, Store, UsageRow } from "./types.ts";
export interface D1Result { success: boolean; meta?: { changes?: number }; }
export interface D1Rows<T> { results: T[]; }
export interface D1Statement { bind(...values: unknown[]): D1Statement; run(): Promise<D1Result>; first<T>(): Promise<T | null>; all<T>(): Promise<D1Rows<T>>; }
export interface D1DatabaseLike { prepare(sql: string): D1Statement; }

type DbOperation = Record<string, unknown>;
type SchemaRow = { name:string; sql:string|null };
type MigrationRow = { version:number; name:string; checksum:string; applied_at:number };
export const FINANCIAL_SCHEMA_VERSION=1;
const BASELINE_MIGRATION_NAME="financial_recovery_baseline";
const OP_STATES:FinancialOperationState[]=["CREATED","COST_RESERVED","PAYMENT_AUTHORIZED","UPSTREAM_STARTED","RESULT_ESCROWED","SETTLEMENT_PENDING","SETTLEMENT_AMBIGUOUS","SETTLED","RESULT_RELEASED","RECOVERY_REQUIRED","FAILED_FINAL"];
const ALLOWED_TRANSITIONS:Record<FinancialOperationState,readonly FinancialOperationState[]>={CREATED:["COST_RESERVED","FAILED_FINAL"],COST_RESERVED:["PAYMENT_AUTHORIZED","FAILED_FINAL"],PAYMENT_AUTHORIZED:["UPSTREAM_STARTED","FAILED_FINAL"],UPSTREAM_STARTED:["RESULT_ESCROWED","RECOVERY_REQUIRED","FAILED_FINAL"],RESULT_ESCROWED:["SETTLEMENT_PENDING","SETTLED","FAILED_FINAL"],SETTLEMENT_PENDING:["SETTLEMENT_AMBIGUOUS","SETTLED","RECOVERY_REQUIRED","FAILED_FINAL"],SETTLEMENT_AMBIGUOUS:["SETTLED","RECOVERY_REQUIRED","FAILED_FINAL"],SETTLED:["RESULT_RELEASED","RECOVERY_REQUIRED"],RESULT_RELEASED:[],RECOVERY_REQUIRED:["RECOVERY_REQUIRED","SETTLED","FAILED_FINAL"],FAILED_FINAL:[]};

export class D1FinancialStore implements Store {
  private db:D1DatabaseLike; constructor(db:D1DatabaseLike){this.db=db;}
  async ensureSchema():Promise<void>{
    // This is deliberately a single, explicit baseline.  Do not silently
    // repair a partly different ledger: financial schema drift must fail
    // closed until it has been reviewed and migrated explicitly.
    const tables:[string,string][]=[
      "CREATE TABLE IF NOT EXISTS usage (request_id TEXT PRIMARY KEY, product_id TEXT NOT NULL, identity_kind TEXT NOT NULL, identity_value TEXT NOT NULL, occurred_at INTEGER NOT NULL, cost REAL NOT NULL CHECK(cost>=0), state TEXT NOT NULL CHECK(state IN ('RESERVED','FINALIZED')))",
      "CREATE TABLE IF NOT EXISTS financial_operations (operation_id TEXT PRIMARY KEY,request_id TEXT NOT NULL UNIQUE,requirement_id TEXT NOT NULL UNIQUE,product_id TEXT NOT NULL,request_hash TEXT NOT NULL,artifact_hash TEXT NOT NULL,payment_provider TEXT NOT NULL,payment_reference TEXT NOT NULL,requirement_json TEXT NOT NULL,payer TEXT NOT NULL,reservation_id TEXT NOT NULL UNIQUE,upstream_operation_id TEXT NOT NULL UNIQUE,settlement_id TEXT NOT NULL UNIQUE,state TEXT NOT NULL CHECK(state IN ('CREATED','COST_RESERVED','PAYMENT_AUTHORIZED','UPSTREAM_STARTED','RESULT_ESCROWED','SETTLEMENT_PENDING','SETTLEMENT_AMBIGUOUS','SETTLED','RESULT_RELEASED','RECOVERY_REQUIRED','FAILED_FINAL')),authorized_amount REAL NOT NULL CHECK(authorized_amount>=0),reserved_amount REAL NOT NULL CHECK(reserved_amount>=0),actual_cost REAL CHECK(actual_cost IS NULL OR actual_cost>=0),settlement_amount REAL CHECK(settlement_amount IS NULL OR settlement_amount>=0),result_digest TEXT NOT NULL,error_code TEXT NOT NULL,version INTEGER NOT NULL CHECK(version>=0),recovery_owner TEXT NOT NULL,recovery_lease_until INTEGER NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)",
      "CREATE TABLE IF NOT EXISTS result_escrow (operation_id TEXT PRIMARY KEY,result_digest TEXT NOT NULL,payload_json TEXT NOT NULL,payload_size INTEGER NOT NULL CHECK(payload_size>=0),created_at INTEGER NOT NULL,expires_at INTEGER NOT NULL,released_at INTEGER)",
      "CREATE TABLE IF NOT EXISTS settlement_outbox (settlement_id TEXT PRIMARY KEY,operation_id TEXT NOT NULL UNIQUE,payment_provider TEXT NOT NULL,amount REAL NOT NULL CHECK(amount>=0),status TEXT NOT NULL CHECK(status IN ('PENDING','AMBIGUOUS','SETTLED','FINAL_FAILURE')),attempt_count INTEGER NOT NULL CHECK(attempt_count>=0),last_attempt_at INTEGER,provider_reference TEXT NOT NULL,last_error_code TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)",
      "CREATE TABLE IF NOT EXISTS financial_incidents (id INTEGER PRIMARY KEY AUTOINCREMENT,operation_id TEXT NOT NULL,kind TEXT NOT NULL,detail TEXT NOT NULL,created_at INTEGER NOT NULL)",
      "CREATE TABLE IF NOT EXISTS financial_product_halts (product_id TEXT PRIMARY KEY,reason TEXT NOT NULL,operation_id TEXT NOT NULL,created_at INTEGER NOT NULL)"
      ,"CREATE TABLE IF NOT EXISTS payment_proofs (operation_id TEXT PRIMARY KEY,payload_json TEXT NOT NULL,payload_size INTEGER NOT NULL CHECK(payload_size>0 AND payload_size<=131072),created_at INTEGER NOT NULL,expires_at INTEGER NOT NULL)"
    ].map(sql=>[sql.match(/CREATE TABLE IF NOT EXISTS ([a-z_]+)/)?.[1]??"",sql]);
    const canonical=(sql:string)=>sql.toLowerCase().replace(/create\s+table\s+if\s+not\s+exists/g,"create table").replace(/[\s`"'\[\]]/g,"");
    const expectedChecksum=Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(tables.map(([name,sql])=>`${name}:${canonical(sql)}`).join("\n"))))).map(v=>v.toString(16).padStart(2,"0")).join("");
    const metadata="CREATE TABLE IF NOT EXISTS moneyai_schema_migrations (version INTEGER PRIMARY KEY,name TEXT NOT NULL,checksum TEXT NOT NULL,applied_at INTEGER NOT NULL)";
    const metadataResult=await this.db.prepare(metadata).run();
    if(!metadataResult.success)throw new Error("financial schema migration metadata initialization failed");
    const migrations=await this.db.prepare("SELECT version,name,checksum,applied_at FROM moneyai_schema_migrations ORDER BY version").all<MigrationRow>();
    const schemaRows=await this.db.prepare("SELECT name,sql FROM sqlite_master WHERE type='table' AND name IN ('usage','financial_operations','result_escrow','settlement_outbox','financial_incidents','financial_product_halts','payment_proofs')").all<SchemaRow>();
    const actual=new Map(schemaRows.results.map(row=>[row.name,row.sql??""]));
    const matchesBaseline=actual.size===tables.length&&tables.every(([name,sql])=>canonical(actual.get(name)??"")===canonical(sql));
    if(migrations.results.length===0){
      // Empty D1 gets the baseline; a complete matching pre-versioned D1 is
      // adopted once.  Any other state is an unsafe, non-destructive block.
      if(actual.size===0){for(const [,sql] of tables){const r=await this.db.prepare(sql).run();if(!r.success)throw new Error("financial baseline migration failed");}}
      else if(!matchesBaseline)throw new Error("financial baseline adoption refused: existing D1 schema differs");
      const inserted=await this.db.prepare("INSERT OR IGNORE INTO moneyai_schema_migrations(version,name,checksum,applied_at) VALUES(?,?,?,?)").bind(FINANCIAL_SCHEMA_VERSION,BASELINE_MIGRATION_NAME,expectedChecksum,Date.now()).run();
      if(!inserted.success)throw new Error("financial baseline migration record failed");
    }
    const recorded=await this.db.prepare("SELECT version,name,checksum,applied_at FROM moneyai_schema_migrations WHERE version=?").bind(FINANCIAL_SCHEMA_VERSION).first<MigrationRow>();
    if(migrations.results.length>1||!recorded||recorded.name!==BASELINE_MIGRATION_NAME||recorded.checksum!==expectedChecksum)throw new Error("financial schema version or checksum mismatch");
    const verified=await this.db.prepare("SELECT name,sql FROM sqlite_master WHERE type='table' AND name IN ('usage','financial_operations','result_escrow','settlement_outbox','financial_incidents','financial_product_halts','payment_proofs')").all<SchemaRow>();
    const verifiedActual=new Map(verified.results.map(row=>[row.name,row.sql??""]));
    if(verifiedActual.size!==tables.length||!tables.every(([name,sql])=>canonical(verifiedActual.get(name)??"")===canonical(sql)))throw new Error("financial schema drift detected");
  }
  async reserveCost(requestId:string,row:UsageRow,l:{perRequest:number;daily:number;monthly:number;perProductDaily:number;perUserDaily:number}):Promise<boolean>{
    if(!Number.isFinite(row.cost)||row.cost<0||row.cost>l.perRequest)return false;await this.ensureSchema();const d=86_400_000;
    const sql=`INSERT INTO usage(request_id,product_id,identity_kind,identity_value,occurred_at,cost,state) SELECT ?,?,?,?,?,?,'RESERVED' WHERE
      (SELECT COALESCE(SUM(cost),0) FROM usage WHERE occurred_at>=?)+?<=? AND
      (SELECT COALESCE(SUM(cost),0) FROM usage WHERE occurred_at>=?)+?<=? AND
      (SELECT COALESCE(SUM(cost),0) FROM usage WHERE occurred_at>=? AND product_id=?)+?<=? AND
      (SELECT COALESCE(SUM(cost),0) FROM usage WHERE occurred_at>=? AND product_id=? AND identity_kind=? AND identity_value=?)+?<=?`;
    const r=await this.db.prepare(sql).bind(requestId,row.productId,row.identityKind,row.identityValue,row.occurredAt,row.cost,row.occurredAt-d,row.cost,l.daily,row.occurredAt-30*d,row.cost,l.monthly,row.occurredAt-d,row.productId,row.cost,l.perProductDaily,row.occurredAt-d,row.productId,row.identityKind,row.identityValue,row.cost,l.perUserDaily).run();
    return r.success&&(r.meta?.changes??0)===1;
  }
  async finalizeCost(id:string,cost:number):Promise<void>{
    if(!Number.isFinite(cost)||cost<0)throw new Error("invalid actual cost");
    const r=await this.db.prepare("UPDATE usage SET cost=?,state='FINALIZED' WHERE request_id=? AND state='RESERVED' AND cost>=?").bind(cost,id,cost).run();
    if(r.success&&(r.meta?.changes??0)===1)return;
    const prior=await this.db.prepare("SELECT cost,state FROM usage WHERE request_id=?").bind(id).first<{cost:number;state:string}>();
    if(prior?.state==="FINALIZED"&&Number(prior.cost)===cost)return;
    throw new Error("reservation finalization failed");
  }
  async releaseCost(id:string):Promise<void>{await this.db.prepare("DELETE FROM usage WHERE request_id=? AND state='RESERVED'").bind(id).run();}
  async recordUsage(row:UsageRow):Promise<void>{const id=crypto.randomUUID();if(!await this.reserveCost(id,row,{perRequest:Number.MAX_VALUE,daily:Number.MAX_VALUE,monthly:Number.MAX_VALUE,perProductDaily:Number.MAX_VALUE,perUserDaily:Number.MAX_VALUE}))throw new Error("usage reserve failed");await this.finalizeCost(id,row.cost);}
  async sumCost(since:number,productId?:string,identity?:[string,string]):Promise<number>{await this.ensureSchema();let sql="SELECT COALESCE(SUM(cost),0) AS total FROM usage WHERE occurred_at>=?";const args:unknown[]=[since];if(productId){sql+=" AND product_id=?";args.push(productId);}if(identity){sql+=" AND identity_kind=? AND identity_value=?";args.push(...identity);}const row=await this.db.prepare(sql).bind(...args).first<{total:number}>();return Number(row?.total??0);}
  async countRequests(productId:string,kind:string,value:string,since:number):Promise<number>{await this.ensureSchema();const row=await this.db.prepare("SELECT COUNT(*) AS total FROM usage WHERE product_id=? AND identity_kind=? AND identity_value=? AND occurred_at>=?").bind(productId,kind,value,since).first<{total:number}>();return Number(row?.total??0);}
  private operation(row:DbOperation|null):FinancialOperation|null{return row?{operationId:String(row.operation_id),requestId:String(row.request_id),requirementId:String(row.requirement_id),productId:String(row.product_id),requestHash:String(row.request_hash),artifactHash:String(row.artifact_hash),paymentProvider:String(row.payment_provider),paymentReference:String(row.payment_reference),requirementJson:String(row.requirement_json),payer:String(row.payer),reservationId:String(row.reservation_id),upstreamOperationId:String(row.upstream_operation_id),settlementId:String(row.settlement_id),state:String(row.state) as FinancialOperationState,authorizedAmount:Number(row.authorized_amount),reservedAmount:Number(row.reserved_amount),actualCost:row.actual_cost===null?null:Number(row.actual_cost),settlementAmount:row.settlement_amount===null?null:Number(row.settlement_amount),resultDigest:String(row.result_digest),errorCode:String(row.error_code),version:Number(row.version),recoveryOwner:String(row.recovery_owner),recoveryLeaseUntil:Number(row.recovery_lease_until),createdAt:Number(row.created_at),updatedAt:Number(row.updated_at)}:null;}
  async createOperation(o:FinancialOperation):Promise<boolean>{await this.ensureSchema();if(!OP_STATES.includes(o.state))return false;const r=await this.db.prepare("INSERT OR IGNORE INTO financial_operations(operation_id,request_id,requirement_id,product_id,request_hash,artifact_hash,payment_provider,payment_reference,requirement_json,payer,reservation_id,upstream_operation_id,settlement_id,state,authorized_amount,reserved_amount,actual_cost,settlement_amount,result_digest,error_code,version,recovery_owner,recovery_lease_until,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(o.operationId,o.requestId,o.requirementId,o.productId,o.requestHash,o.artifactHash,o.paymentProvider,o.paymentReference,o.requirementJson,o.payer,o.reservationId,o.upstreamOperationId,o.settlementId,o.state,o.authorizedAmount,o.reservedAmount,o.actualCost,o.settlementAmount,o.resultDigest,o.errorCode,o.version,o.recoveryOwner,o.recoveryLeaseUntil,o.createdAt,o.updatedAt).run();return r.success&&(r.meta?.changes??0)===1;}
  async getOperation(id:string):Promise<FinancialOperation|null>{await this.ensureSchema();return this.operation(await this.db.prepare("SELECT * FROM financial_operations WHERE operation_id=?").bind(id).first<DbOperation>());}
  async transitionOperation(id:string,v:number,states:FinancialOperationState[],next:FinancialOperationState,p:Partial<FinancialOperation>={}):Promise<boolean>{
    if(!states.length||!states.every(s=>OP_STATES.includes(s))||!OP_STATES.includes(next)||!states.every(s=>ALLOWED_TRANSITIONS[s].includes(next))){await this.recordFinancialIncident(id,"INVALID_STATE_TRANSITION",`${states.join("|")} -> ${next}`);return false;}
    const marks=states.map(()=>"?").join(",");const sql=`UPDATE financial_operations SET state=?,payment_reference=COALESCE(?,payment_reference),requirement_json=COALESCE(?,requirement_json),payer=COALESCE(?,payer),authorized_amount=COALESCE(?,authorized_amount),actual_cost=COALESCE(?,actual_cost),settlement_amount=COALESCE(?,settlement_amount),result_digest=COALESCE(?,result_digest),error_code=COALESCE(?,error_code),version=version+1,updated_at=? WHERE operation_id=? AND version=? AND state IN (${marks})`;
    const r=await this.db.prepare(sql).bind(next,p.paymentReference??null,p.requirementJson??null,p.payer??null,p.authorizedAmount??null,p.actualCost??null,p.settlementAmount??null,p.resultDigest??null,p.errorCode??null,Date.now(),id,v,...states).run();return r.success&&(r.meta?.changes??0)===1;
  }
  async saveEscrow(e:ResultEscrowRow):Promise<boolean>{await this.ensureSchema();const r=await this.db.prepare("INSERT OR IGNORE INTO result_escrow(operation_id,result_digest,payload_json,payload_size,created_at,expires_at,released_at) VALUES(?,?,?,?,?,?,?)").bind(e.operationId,e.resultDigest,e.payloadJson,e.payloadSize,e.createdAt,e.expiresAt,e.releasedAt).run();return r.success&&(r.meta?.changes??0)===1;}
  async getEscrow(id:string):Promise<ResultEscrowRow|null>{await this.ensureSchema();const r=await this.db.prepare("SELECT * FROM result_escrow WHERE operation_id=?").bind(id).first<Record<string,unknown>>();return r?{operationId:String(r.operation_id),resultDigest:String(r.result_digest),payloadJson:String(r.payload_json),payloadSize:Number(r.payload_size),createdAt:Number(r.created_at),expiresAt:Number(r.expires_at),releasedAt:r.released_at===null?null:Number(r.released_at)}:null;}
  async markEscrowReleased(id:string,at:number):Promise<void>{await this.db.prepare("UPDATE result_escrow SET released_at=COALESCE(released_at,?) WHERE operation_id=?").bind(at,id).run();}
  async createSettlementOutbox(o:SettlementOutboxRow):Promise<boolean>{await this.ensureSchema();const r=await this.db.prepare("INSERT OR IGNORE INTO settlement_outbox(settlement_id,operation_id,payment_provider,amount,status,attempt_count,last_attempt_at,provider_reference,last_error_code,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").bind(o.settlementId,o.operationId,o.paymentProvider,o.amount,o.status,o.attemptCount,o.lastAttemptAt,o.providerReference,o.lastErrorCode,o.createdAt,o.updatedAt).run();return r.success&&(r.meta?.changes??0)===1;}
  async getSettlementOutbox(id:string):Promise<SettlementOutboxRow|null>{await this.ensureSchema();const r=await this.db.prepare("SELECT * FROM settlement_outbox WHERE settlement_id=?").bind(id).first<Record<string,unknown>>();return r?{settlementId:String(r.settlement_id),operationId:String(r.operation_id),paymentProvider:String(r.payment_provider),amount:Number(r.amount),status:String(r.status) as SettlementOutboxStatus,attemptCount:Number(r.attempt_count),lastAttemptAt:r.last_attempt_at===null?null:Number(r.last_attempt_at),providerReference:String(r.provider_reference),lastErrorCode:String(r.last_error_code),createdAt:Number(r.created_at),updatedAt:Number(r.updated_at)}:null;}
  async updateSettlementOutbox(id:string,status:SettlementOutboxStatus,error="",providerReference=""):Promise<void>{const r=await this.db.prepare("UPDATE settlement_outbox SET status=?,attempt_count=attempt_count+1,last_attempt_at=?,provider_reference=CASE WHEN ?='' THEN provider_reference ELSE ? END,last_error_code=?,updated_at=? WHERE settlement_id=?").bind(status,Date.now(),providerReference,providerReference,error,Date.now(),id).run();if(!r.success||(r.meta?.changes??0)!==1)throw new Error("settlement outbox update failed");}
  async claimRecovery(id:string,owner:string,now:number,until:number):Promise<boolean>{const r=await this.db.prepare("UPDATE financial_operations SET recovery_owner=?,recovery_lease_until=?,version=version+1,updated_at=? WHERE operation_id=? AND (recovery_lease_until<=? OR recovery_owner=?)").bind(owner,until,now,id,now,owner).run();return r.success&&(r.meta?.changes??0)===1;}
  async releaseRecovery(id:string,owner:string):Promise<void>{await this.db.prepare("UPDATE financial_operations SET recovery_owner='',recovery_lease_until=0,version=version+1,updated_at=? WHERE operation_id=? AND recovery_owner=?").bind(Date.now(),id,owner).run();}
  async recordFinancialIncident(id:string,kind:string,detail:string):Promise<void>{await this.ensureSchema();await this.db.prepare("INSERT INTO financial_incidents(operation_id,kind,detail,created_at) VALUES(?,?,?,?)").bind(id,kind,detail.slice(0,300),Date.now()).run();}
  async isProductHalted(productId:string):Promise<boolean>{await this.ensureSchema();return!!await this.db.prepare("SELECT product_id FROM financial_product_halts WHERE product_id=?").bind(productId).first();}
  async listRecoverableOperations(limit:number):Promise<FinancialOperation[]>{await this.ensureSchema();const rows=await this.db.prepare("SELECT * FROM financial_operations WHERE state IN ('UPSTREAM_STARTED','RESULT_ESCROWED','SETTLEMENT_PENDING','SETTLEMENT_AMBIGUOUS','SETTLED','RECOVERY_REQUIRED') ORDER BY updated_at LIMIT ?").bind(Math.max(1,Math.min(limit,100))).all<DbOperation>();return rows.results.map(row=>this.operation(row)).filter((row):row is FinancialOperation=>row!==null);}
  async recoverExpiredSafeReservations(cutoff:number):Promise<number>{await this.ensureSchema();const marked=await this.db.prepare("UPDATE financial_operations SET state='FAILED_FINAL',error_code='EXPIRED_SAFE_RESERVATION',version=version+1,updated_at=? WHERE updated_at<? AND state IN ('CREATED','COST_RESERVED','PAYMENT_AUTHORIZED')").bind(Date.now(),cutoff).run();await this.db.prepare("DELETE FROM usage WHERE state='RESERVED' AND request_id IN (SELECT reservation_id FROM financial_operations WHERE state='FAILED_FINAL' AND error_code='EXPIRED_SAFE_RESERVATION')").run();return Number(marked.meta?.changes??0);}
  async savePaymentProof(id:string,payloadJson:string,expiresAt:number):Promise<boolean>{await this.ensureSchema();const size=new TextEncoder().encode(payloadJson).length;if(size<1||size>131072||expiresAt<=Date.now())return false;const r=await this.db.prepare("INSERT OR IGNORE INTO payment_proofs(operation_id,payload_json,payload_size,created_at,expires_at) VALUES(?,?,?,?,?)").bind(id,payloadJson,size,Date.now(),expiresAt).run();return r.success&&(r.meta?.changes??0)===1;}
  async getPaymentProof(id:string):Promise<string|null>{await this.ensureSchema();const row=await this.db.prepare("SELECT payload_json FROM payment_proofs WHERE operation_id=? AND expires_at>?").bind(id,Date.now()).first<{payload_json:string}>();return row?.payload_json??null;}
  async deletePaymentProof(id:string):Promise<void>{await this.db.prepare("DELETE FROM payment_proofs WHERE operation_id=?").bind(id).run();}
  // H-01: each purge step is independent, so one failing statement cannot skip
  // the remaining cleanup for the whole batch.
  async purgeExpiredSensitiveData(now:number):Promise<number>{await this.ensureSchema();let purged=0;const steps:[string,unknown[]][]=[["DELETE FROM payment_proofs WHERE expires_at<=?",[now]],["DELETE FROM result_escrow WHERE expires_at<=? AND released_at IS NOT NULL",[now]]];for(const [sql,args]of steps){try{const r=await this.db.prepare(sql).bind(...args).run();purged+=Number(r.meta?.changes??0);}catch{/* next step still runs */}}return purged;}
  async listOperationsForReconciliation(limit:number):Promise<FinancialOperation[]>{await this.ensureSchema();const rows=await this.db.prepare("SELECT * FROM financial_operations WHERE state IN ('SETTLED','RESULT_RELEASED','FAILED_FINAL') ORDER BY updated_at DESC LIMIT ?").bind(Math.max(1,Math.min(limit,100))).all<DbOperation>();return rows.results.map(row=>this.operation(row)).filter((row):row is FinancialOperation=>row!==null);}
  async reconcileOperation(id:string):Promise<{ok:boolean;detail:string}>{await this.ensureSchema();const op=await this.getOperation(id);if(!op)return{ok:false,detail:"operation missing"};const problems:string[]=[];if(!Number.isFinite(op.reservedAmount)||op.reservedAmount<0)problems.push("invalid reserved amount");if(op.actualCost!==null&&(!Number.isFinite(op.actualCost)||op.actualCost<0||op.actualCost>op.reservedAmount))problems.push("actual cost violates reservation");const usage=await this.db.prepare("SELECT cost,state FROM usage WHERE request_id=?").bind(op.reservationId).first<{cost:number;state:string}>();const active=["COST_RESERVED","PAYMENT_AUTHORIZED","UPSTREAM_STARTED","RESULT_ESCROWED","SETTLEMENT_PENDING","SETTLEMENT_AMBIGUOUS","RECOVERY_REQUIRED"].includes(op.state);if(active&&(!usage||usage.state!=="RESERVED"||Math.abs(Number(usage.cost)-op.reservedAmount)>1e-9))problems.push("active reservation mismatch");if(["SETTLED","RESULT_RELEASED"].includes(op.state)){if(op.actualCost===null||!usage||usage.state!=="FINALIZED"||Math.abs(Number(usage.cost)-op.actualCost)>1e-9)problems.push("finalized cost mismatch");else{const released=op.reservedAmount-op.actualCost;if(released<0||Math.abs(op.actualCost+released-op.reservedAmount)>1e-9)problems.push("ledger conservation mismatch");}}if(["RESULT_ESCROWED","SETTLEMENT_PENDING","SETTLEMENT_AMBIGUOUS","SETTLED","RESULT_RELEASED","RECOVERY_REQUIRED"].includes(op.state)&&!await this.getEscrow(id))problems.push("result escrow missing");if(["SETTLEMENT_PENDING","SETTLEMENT_AMBIGUOUS","SETTLED","RESULT_RELEASED","RECOVERY_REQUIRED"].includes(op.state)&&!await this.getSettlementOutbox(op.settlementId))problems.push("settlement outbox missing");if(!problems.length)return{ok:true,detail:"ledger conserved"};const detail=problems.join("; ");await this.recordFinancialIncident(id,"FINANCIAL_LEDGER_MISMATCH",detail);await this.db.prepare("INSERT OR IGNORE INTO financial_product_halts(product_id,reason,operation_id,created_at) VALUES(?,?,?,?)").bind(op.productId,"FINANCIAL_LEDGER_MISMATCH",id,Date.now()).run();return{ok:false,detail};}
  async getCache():Promise<CacheRow|null>{return null;}async setCache():Promise<void>{}
  async getCircuit():Promise<CircuitRow|null>{return null;}async setCircuit():Promise<void>{}
}
